---
title: "Statistical Inference"
subtitle: |
  Discussion Group
author:
  - name: "Chi-Kuang Yeh"
    affiliation: "Georgia State University"
date: today
date-format: "DD MMMM, YYYY"

format:
  html:
    theme: readable
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    css: styles.css
    include-in-header: header.html

editor: visual
---

*Disclaimer: These notes have not been subjected to the usual scrutiny reserved for formal publications. They may be distributed outside this class only with the permission of the Instructor.*

# Meeting time

-   9:00 - 11:00 Tuesday (Online) and 10:00 - 12:00 Friday

# 2025 Timeline

| Status | Date | Notes | Topic |
|:----------------:|:----------------:|:----------------:|------------------|
| ✅ Complete | Sep 26 | 1 | Multivariate Normal |
| ✅ Complete | Oct 3 | 2 | $\chi^2$ distribution |
| ✅ Complete | Oct 10 | 3 | Asymptotic modes |
| ✅ Complete | Oct 14 | 4 | Big O pee and small O pee |
| ✅ Complete | Oct 17 | 5 | Relationship of Big O and Small O, with convergence modes |
| ✅ Complete | Oct 21 | 6 | CMT and Slutsky's Theorem |
| ✅ Complete | Oct 24 | 7 | Wald point estimation |
| ✅ Complete | Oct 28 | 8 | Wald confidence interval |
| ✅ Complete | Oct 31 | \- | Georgia Statistics Day |
| ✅ Complete | Nov 4 | 9 | Asymptotic Distribution of $\hat{\theta}_n$ |
| ✅ Complete | Nov 7 | \- | Colloquium |
| ✅ Complete  | Nov 11 | 10 | Likelihood Ration Test |
| ✅ Complete  | Nov 14 | 11 | Regularity conditions of MLE |
| ✅ Complete  | Nov 18 | 12 | Moments |
| ⏳ In Progress  | Nov 21 | 13 | Quantile |
| 🔜 Planned | Nov 25 | 14 |  |

# Table of Content

**Chapter 0 Multivariate Normal Distribution**

-   [x] 0.1 Definition

-   [x] 0.2 Properties of $N_p(\mu,\Sigma)$

-   [x] 0.3 Quadratic form of $N_P(\mu,\Sigma)$

**Chapter 1 Review of Probability Theory**

-   [x] 1.1 $\sigma$-algebra and Probability Function

-   [x] 1.2 Random Variables

-   [x] 1.3 Expectation

**Chapter 2 Asymptotic Theory**

-   [x] 2.1 Mode of Convergence

-   [x] 2.2 Convergence in Distribution and Central Limit Theorem

-   [x] 2.3 Stochastic Order: Big $O$ and small $o$

-   [x] 2.4 Convergence of Transformation and Slutsky's Theorem

**Chapter 3 Parametric Likelihood Method**

-   [x] 3.1 Strong Consistency of MLE

    -   [x] Wald point estimation
    -   [x] Wald confidence interval

-   [x] 3.2 Asymptotic Distribution of $\hat{\theta}_n$

-   [x] 3.3 Limiting Distribution of Likelihood Ration Test

**Chapter 4 Empirical CDF, Moments and Quantile**

-   [x] 4.1 Empirical cdf and properties

-   [ ] 4.2 Sample Moments

-   [ ] 4.3 Sample Quantiles

**Chapter 5 Empirical Likelihood Method**

-   [ ] 5.1 Ideas for Empirical Likelihood

-   [ ] 5.2 Empirical likelihood for mean of population

    -   [ ] Main results
    -   [ ] Numerical Implementation
    -   [ ] Proof of main results

-   [ ] 5.3 Empirical likelihood for estimating equation

**Chapter 6 Bootsrap**

-   [ ] 6.1 Introduction

-   [ ] 6.2 Nonparametric Bootstrap method

-   [ ] 6.3 Bootstrap Estimation of sampling distribution

-   [ ] 6.4 Bootstrap confidence interval

-   [ ] 6.5 Some theoretical results

    -   [ ] Consistency property of $H_{Boot}(x)$
    -   [ ] consistency property of $V_{boot}$
    -   [ ] Asymptotic results for Bootstrap CI

# Credit

The notes is based on Prof. [Pengfei Li](https://uwaterloo.ca/statistics-and-actuarial-science/profiles/pengfei-li) from UWaterloo's lecture notes for STAT 908 course.
