---
title: "Job Market reflection"
date: "2026-02-12"
description: "For Tenure-Track Statistics Professorship in North America"
tags: ["Personal", "Job"]
categories: ["resources"]
math: true
output: blogdown::html_page
---

This is just a self-reflection of the job market process for *tenure-track statistics/biostatistics professorship* in North America of the academic year 2024--2025. I am adding more details as I go through the process. I hope this can help other job seekers in the future, especially for the ones coming from Canada and do not have any connections or experiences in the US.

# Profile

## Identity

I am a Taiwanese-Canadian, and do not have the US passport. I came to Canada during the middle school, and stayed there for around 20 years. I did all my educations in Canada, including middle school, high-school, Bachelor, Masters and PhD. I do not have any US connections, nor any US experiences (e.g., internship, postdoc etc.).

## Publication

At the time, I had **4** published papers, **1** paper in revision, **2** papers submitted, and quite a few papers in preparation (with draft available). I do not have any TOP papers (e.g., JASA, JRSS-B, AoS etc.), nor any machine learning proceedings.

## Teaching Experience

I think teaching experience is very important in North America. I had a long history of being a TA and grader, which is like 12+ years. I taught one full course before (a 3-credit undergraduate course on Probability), a guest lecture, and co-developed one course (Introduction to Data Science).

## Mentoring Experience

I think it is somewhat important but it is not necessary. I have mentored two PhD students, and other undergraduate students (but I did not write the undergraduates on my CV).

## Research Directions

My publications span across a few areas, including functional data analysis, Optimal design of experiment, statistical machine learning and high-dimensional statistics, with applications span on neuroscience, drug development and toxicology. Those areas are not really coherent, and have an unified theme, so it may be difficult to convince the search committee that I have a clear research direction.


# My Thinking Process

I did all my educations in Canada, including middle school, high-school, Bachelor, Masters and PhD. Hence I do not have much of connections in the US. On the other hand, I have strong connections in Canada, and being a Canadian is a hugh plus. Unfortunately, this year, Canadian universities are not hiring much, only roughly around 10 schools have openings.

I know I am **not a top candidate**. Hence I have to apply as many positions as possible, to just have a slim chance. I applied to **80+** positions, including both Canada and the US. I applied to all the positions that I am qualified for, though I know that I do not have much of chance in Biostatistics and Top schools (e.g., Princeton, Harvard, Stanford, Columbia etc.). I can apply more, but the job market was not so good due to various reasons including the budget cuts and hiring freeze.

The research statement was a big headache for me, as I alluded before, my research directions are not very coherent. I tried to make it as coherent as possible, but I know it is not perfect. I also tried to make it as accessible as possible, so that non-statisticians can understand it. I also tried to make it as exciting as possible, by highlighting the impact of my research. I also tried to make it as future-oriented as possible, by highlighting the potential future directions of my research. Some of the researches/papers were not highlighted or introduced as they did not really fit into the theme of my research statement, for instance, the optimal design of experiment, the area I had the most publications on.

# Some suggestions

1. Prepare as early as possible

2. Always have your CV up-to-date

3. Think about the long term plan

4. Get teaching experience as early as possible

5. Get mentoring experience as early as possible

6. Build connections

7. Think about your reference letters, and the teaching reference

# Interview

I had more than **10** online interviews, and only 1 of them that I did not make into the 2nd round (in person). Of course, I got many many rejection letters.

## Online interviews

For all the online interviews, I wrote a **script** for myself, and practiced it multiple times, especially the first few. Specifically,  

1. Prepared some **questions** to ask the search committee, and practiced answering some common questions. 
2. I also made sure that my **internet connection** is stable
3. Check my **background** is clean and professional. 
4. Make sure that my **camera** is at the right height, so that I am looking at the camera when I am talking. 
5. I also made sure that my **lighting** is good, so that my face is well-lit. 
6. I also made sure that my **microphone** is working well, so that my voice is clear. 
7. I use MacBook, so I logoff my iCloud in case there is an incoming call.

## In person interview

This is sometime referred as the `flyout`, `onsite` or `campus visit`.


### Dress

I've heard some suggestions that it is the academic interview, so do not need to be that formal. However, I think it is better to be formal than informal. I wore a **suit and tie** for everything interview, and I think it is a good choice. It is better to be overdressed than underdressed.

## After the interview

I will send a *thank you* email to each of the person I met during the process, not only the search committee. Maybe I have an above average memeory, I can remember the name of each person I met, and the conversation we had. I will also send a thank you email to the search committee, and mention some specific things that I talked about during the interview, to show that I was paying attention and that I am interested in the position. 

But one thing that can come up is, if there are many interviews going back to back, it can be hard to remember the details of each interview, and it can be hard to write a personalized thank you email for each of them. In that case, I will try to write down on my planner during our meeting, and so I can send a personalized thank you email to each of them. I will also try to send the thank you email as soon as possible, ideally within 24 hours after the interview, so that it is still fresh in their mind. However, during the travel, it may be delayed which is not ideal.

## Offer and Neogiation

The offer is usually made by the chair of the search committee, and it is usually a **verbal offer** first, followed by a written offer. The verbal offer is usually made during the interview, and it is usually a good sign that you are the top candidate. However, it is not a guarantee that you will get the offer, as there may be some last minute changes or issues. The written offer is usually made after the interview, and it is usually a formal document that outlines the terms of the offer, including the salary, start-up package, teaching load, etc. 

During the verbal offer, the chair may start to list down the details of the upcoming offer to you. For instance, the salary, the start-up package, the teaching load, the tenure clock, etc. It is important to listen carefully to the details of the offer, and to ask any questions that you may have. It is also important to express your gratitude for the offer, and to let them know that you are interested in the position. However, it is also important to let them know that you need some time to think about the offer, and to discuss it with your family and mentors. It is usually acceptable to ask for a few days to a week to think about the offer, but it is important to be respectful of their timeline, as they may have other candidates that they are considering as well. Some may be more **pushy** than the others, but it is important to be firm and assertive, and to let them know that you need some time to think about the offer. It may be difficult to do it in practice, unfortunately.

## Expectation and Timeline for the tenure

In most of the departments if all, there should be document that contains the outline of the expectation. Those can include

+ funding requirement
+ the teaching requirement
+ the service requirement
+ student supervision requirement
+ Others


It is ultraimportant to read this document carefully, and to understand what is expected of you as a tenure-track faculty member. It is also important to ask any questions that you may have about the expectation, and to clarify any doubts that you may have. The timeline for the tenure is usually around 5-7 years, but it can vary depending on the institution and the department. It is important to understand the timeline for the tenure, and to plan your research, teaching and service accordingly.

# TBA

More details will be added

