<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Model Comparison, Partial F Tests, and ANOVA – STAT8561 - Linear Statistical Analysis I</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-de3257830c0d0a37460d18c755b5b021.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom-callouts.css">
<link href="./references.html" rel="next">
<link href="./03_OLS_inference.html" rel="prev">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STAT8561 - Linear Statistical Analysis I</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/chikuang/Teaching-Stat8561"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="././STAT8561---Linear-Statistical-Analysis-I.pdf"> <i class="bi bi-file-pdf" role="img" aria-label="Download PDF">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Model Comparison, Partial F Tests, and ANOVA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_matrix_representation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Matrix Representation and Notation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_LSE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Least Squares Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_OLS_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Distribution Theory of OLS and Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./04.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Model Comparison, Partial F Tests, and ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendix</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./App_A-matrix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Matrix Algebra Review</span></a>
  </div>
</li>
      <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./App_F-quantile-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quantile Regression (Optional)</span></a>
  </div>
</li>
<li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./App_G-mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mixed-Effects Models (Optional)</span></a>
  </div>
</li>
</ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Assessments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Assignment1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Assignment2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 2</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#total-explained-and-unexplained-variation" id="toc-total-explained-and-unexplained-variation" class="nav-link active" data-scroll-target="#total-explained-and-unexplained-variation"><span class="header-section-number">4.1</span> Total, Explained, and Unexplained Variation</a></li>
  <li><a href="#the-overall-f-test" id="toc-the-overall-f-test" class="nav-link" data-scroll-target="#the-overall-f-test"><span class="header-section-number">4.2</span> The Overall F Test</a></li>
  <li><a href="#nested-models" id="toc-nested-models" class="nav-link" data-scroll-target="#nested-models"><span class="header-section-number">4.3</span> Nested Models</a></li>
  <li><a href="#r-demonstration" id="toc-r-demonstration" class="nav-link" data-scroll-target="#r-demonstration"><span class="header-section-number">4.4</span> R Demonstration</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.5</span> Summary</a></li>
  <li><a href="#practice-problems" id="toc-practice-problems" class="nav-link" data-scroll-target="#practice-problems"><span class="header-section-number">4.6</span> Practice Problems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-model-comparison" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Model Comparison, Partial F Tests, and ANOVA</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this chapter, we study the ANOVA decomposition for linear regression, the overall significance test, and the comparison of nested models. These ideas connect the geometry of least squares with the inferential tools developed in earlier chapters.</p>
<blockquote class="blockquote">
<p><strong>Learning Objectives</strong></p>
<p>By the end of this chapter, students should be able to:</p>
<ul>
<li>define the total, regression, and error sums of squares;</li>
<li>explain the ANOVA decomposition in regression with an intercept;</li>
<li>interpret the degrees of freedom associated with SST, SSR, and SSE;</li>
<li>perform the overall <span class="math inline">\(F\)</span> test for regression;</li>
<li>compare nested linear models using extra sums of squares;</li>
<li>interpret ANOVA tables produced by statistical software.</li>
</ul>
</blockquote>
<p><strong>Reading</strong></p>
<p>Recommended reading for this chapter:</p>
<ul>
<li>Seber and Lee:
<ul>
<li>sections on analysis of variance in regression</li>
<li>sums of squares and decomposition of variability</li>
<li>tests for nested models</li>
</ul></li>
<li>Montgomery, Peck, and Vining:
<ul>
<li>sections on the ANOVA table</li>
<li>overall model significance</li>
<li>partial and sequential sums of squares</li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="Motivation: does measuring tree height add useful information?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Motivation: does measuring tree height add useful information?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose a forestry team wants to estimate timber volume before felling a tree. Diameter is already available; measuring height requires additional effort. Does height contribute information beyond diameter?</p>
<p>The real <code>trees</code> dataset in R lets us explore this question with measurements on 31 felled black cherry trees. Consider three candidate mean models:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Information used</th>
<th>Mean volume</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(M_0\)</span></td>
<td>No tree measurements</td>
<td><span class="math inline">\(\beta_0\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(M_1\)</span></td>
<td>Diameter</td>
<td><span class="math inline">\(\beta_0+\beta_1\,\mathrm{Diameter}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(M_2\)</span></td>
<td>Diameter and height</td>
<td><span class="math inline">\(\beta_0+\beta_1\,\mathrm{Diameter}+\beta_2\,\mathrm{Height}\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Discuss before calculating:</strong> Which comparison answers whether height adds information? Why is choosing the smallest training SSE insufficient? Keep these questions in mind; the optional data example below returns to them with fitted models.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tree-measurements" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A leafy tree with arrows marking total height and trunk diameter, measured four feet six inches above the ground. An arrow labelled predict points to stacked timber representing measured volume. The question asks whether height adds information when diameter is known.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tree-measurements-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_files/figure-html/fig-tree-measurements-1.png" class="img-fluid figure-img" alt="A leafy tree with arrows marking total height and trunk diameter, measured four feet six inches above the ground. An arrow labelled predict points to stacked timber representing measured volume. The question asks whether height adds information when diameter is known." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tree-measurements-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: From measurements to a prediction question. Diameter and height are predictors; measured timber volume is the response. The tree and timber drawings are conceptual, not to scale.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Review of the Linear Model</strong></p>
<p>Recall the normal linear model</p>
<p><span class="math display">\[
\mathbf{Y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\varepsilon},
\qquad
\boldsymbol{\varepsilon} \sim N_n(\mathbf{0}, \sigma^2 \mathbf{I}_n).
\]</span></p>
<p>When <span class="math inline">\(\mathbf{X}\)</span> has full column rank, the ordinary least squares estimator is</p>
<p><span class="math display">\[
\hat{\boldsymbol{\beta}}
=
(\mathbf{X}^\top \mathbf{X})^{-1}\mathbf{X}^\top \mathbf{Y},
\]</span></p>
<p>and the fitted values are</p>
<p><span class="math display">\[
\hat{\mathbf{Y}} = \mathbf{X}\hat{\boldsymbol{\beta}}.
\]</span></p>
<p>The residual vector is</p>
<p><span class="math display">\[
\mathbf{e} = \mathbf{Y} - \hat{\mathbf{Y}}.
\]</span></p>
<p>From Chapter 2, we know that <span class="math inline">\(\hat{\mathbf{Y}}\)</span> and <span class="math inline">\(\mathbf{e}\)</span> are orthogonal. From Chapter 3, we know that this leads to useful distributional results for inference. In this chapter, we organize these ideas into the ANOVA framework.</p>
<p><strong>Vector notation.</strong> Following the convention used in this course, <span class="math inline">\(\mathbf a=(a_1,a_2,a_3)\)</span> denotes a column vector, while <span class="math inline">\(\mathbf a^\top=(a_1\;a_2\;a_3)\)</span> denotes a row vector. Commas distinguish the column-vector tuple; spaces separate entries of the row vector.</p>
<section id="total-explained-and-unexplained-variation" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="total-explained-and-unexplained-variation"><span class="header-section-number">4.1</span> Total, Explained, and Unexplained Variation</h2>
<p>A central question in regression is: How much of the variation in the response can be explained by the model? To answer this, we decompose the total variation in <span class="math inline">\(\mathbf{Y}\)</span> into:</p>
<ul>
<li>variation explained by regression;</li>
<li>variation left unexplained by the model.</li>
</ul>
<p>When the model includes an intercept, this decomposition takes a particularly simple and important form.</p>
<div id="def-regression-sums-of-squares" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.1 (Regression Sums of Squares)</strong></span> For an OLS fit with an intercept, let <span class="math inline">\(\bar Y=n^{-1}\sum_{i=1}^nY_i\)</span>, <span class="math inline">\(\hat{\mathbf Y}=\mathbf X\hat{\boldsymbol\beta}\)</span>, and <span class="math inline">\(\mathbf e=\mathbf Y-\hat{\mathbf Y}\)</span>. Define the <strong>total</strong>, <strong>error</strong>, and <strong>regression sums of squares</strong> by</p>
<p><span class="math display">\[
\begin{aligned}
\mathrm{SST}&amp;=\sum_{i=1}^n(Y_i-\bar Y)^2
=\|\mathbf Y-\bar Y\mathbf 1\|^2,\\
\mathrm{SSE}&amp;=\sum_{i=1}^n(Y_i-\hat Y_i)^2
=\mathbf e^\top\mathbf e,\\
\mathrm{SSR}&amp;=\sum_{i=1}^n(\hat Y_i-\bar Y)^2
=\|\hat{\mathbf Y}-\bar Y\mathbf 1\|^2.
\end{aligned}
\]</span></p>
</div>
<p>SST measures variation around the sample mean; SSE measures deviations from the fitted model; SSR measures how much the fitted values vary around the sample mean. These are definitions. Their additive relationship below follows from OLS orthogonality and the inclusion of an intercept.</p>
<div id="thm-anova-decomposition" class="theorem">
<p><span class="theorem-title"><strong>Theorem 4.1 (ANOVA Decomposition with an Intercept)</strong></span> For an ordinary least squares fit whose design matrix contains an intercept,</p>
<p><span class="math display">\[
\mathrm{SST}=\mathrm{SSR}+\mathrm{SSE}.
\]</span></p>
<p>The centered fitted vector <span class="math inline">\(\hat{\mathbf Y}-\bar Y\mathbf 1\)</span> is orthogonal to the residual vector <span class="math inline">\(\mathbf e\)</span>. Thus total variation around the sample mean splits into explained variation and residual variation. This geometric identity does not require normal errors.</p>
</div>
<p><strong>Why the Decomposition Holds</strong></p>
<p>The key reason is orthogonality. We can write</p>
<p><span class="math display">\[
\mathbf{Y} - \bar{Y}\mathbf{1}
=
(\hat{\mathbf{Y}} - \bar{Y}\mathbf{1})
+
(\mathbf{Y} - \hat{\mathbf{Y}}).
\]</span></p>
<p>That is,</p>
<p><span class="math display">\[
\mathbf{Y} - \bar{Y}\mathbf{1}
=
(\hat{\mathbf{Y}} - \bar{Y}\mathbf{1}) + \mathbf{e}.
\]</span></p>
<p>Because the model contains an intercept, the vector <span class="math inline">\(\bar{Y}\mathbf{1}\)</span> lies in the column space of <span class="math inline">\(\mathbf{X}\)</span>. Hence both <span class="math inline">\(\hat{\mathbf{Y}}\)</span> and <span class="math inline">\(\bar{Y}\mathbf{1}\)</span> lie in the model space, so their difference also lies in the model space. Since the residual vector <span class="math inline">\(\mathbf{e}\)</span> is orthogonal to the model space, we have</p>
<p><span class="math display">\[
(\hat{\mathbf{Y}} - \bar{Y}\mathbf{1})^\top \mathbf{e} = 0.
\]</span></p>
<p>Therefore, by the Pythagorean theorem,</p>
<p><span class="math display">\[
\|\mathbf{Y} - \bar{Y}\mathbf{1}\|^2
=
\|\hat{\mathbf{Y}} - \bar{Y}\mathbf{1}\|^2
+
\|\mathbf{e}\|^2,
\]</span></p>
<p>which is exactly</p>
<p><span class="math display">\[
\mathrm{SST} = \mathrm{SSR} + \mathrm{SSE}.
\]</span></p>
<div id="exr-intercept-anova-discussion" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 4.1 (In-Class Discussion: Why Does the Intercept Matter?)</strong></span> Why does the usual centered decomposition <span class="math inline">\(\mathrm{SST}=\mathrm{SSR}+\mathrm{SSE}\)</span> require the model space to contain the constant vector? Which step could fail without an intercept? Does this identity require normal errors?</p>
</div>
<div id="sol-intercept-anova-discussion" class="proof solution">
<p><span class="proof-title"><em>Solution 4.1</em>. </span>With an intercept, <span class="math inline">\(\mathbf 1\)</span> and therefore <span class="math inline">\(\bar Y\mathbf 1\)</span> belong to the model space. Thus the centered fitted vector <span class="math inline">\(\hat{\mathbf Y}-\bar Y\mathbf 1\)</span> is orthogonal to <span class="math inline">\(\mathbf e\)</span>, and the cross term vanishes when its squared norm is expanded. Without a constant vector in the model space, <span class="math inline">\(\sum_i e_i\)</span> need not be zero, so the cross term <span class="math inline">\(\mathbf e^\top(\hat{\mathbf Y}-\bar Y\mathbf 1)=-\bar Y\sum_i e_i\)</span> need not vanish. The identity follows from OLS geometry, not normality.</p>
</div>
<div id="exr-identify-anova-deviations" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 4.2 (In Class: One Observation, Three Deviations)</strong></span> For one observation, <span class="math inline">\(y_i=1\)</span>, <span class="math inline">\(\hat y_i=1.2\)</span>, and <span class="math inline">\(\bar y=3\)</span>. In one minute, identify the total, explained, and residual deviations. Does the squared total deviation equal the sum of the other two squared deviations for this observation?</p>
</div>
<div id="sol-identify-anova-deviations" class="proof solution">
<p><span class="proof-title"><em>Solution 4.2</em>. </span>The deviations are <span class="math inline">\(y_i-\bar y=-2\)</span>, <span class="math inline">\(\hat y_i-\bar y=-1.8\)</span>, and <span class="math inline">\(y_i-\hat y_i=-0.2\)</span>. They add as signed deviations: <span class="math inline">\(-2=-1.8-0.2\)</span>. Their squares do not add: <span class="math inline">\(4\ne3.24+0.04\)</span>. The ANOVA identity holds after summing over all observations because the fitted and residual vectors are orthogonal; it is not a point-by-point identity for squared deviations.</p>
</div>
<p><strong>Degrees of Freedom</strong></p>
<p>The ANOVA decomposition is accompanied by a decomposition of degrees of freedom. When the model includes an intercept and <span class="math inline">\(\mathbf{X}\)</span> has rank <span class="math inline">\(p\)</span>, we have:</p>
<ul>
<li>total degrees of freedom: <span class="math inline">\(n-1\)</span>;</li>
<li>regression degrees of freedom: <span class="math inline">\(p-1\)</span>;</li>
<li>error degrees of freedom: <span class="math inline">\(n-p\)</span>.</li>
</ul>
<p>Thus,</p>
<p><span class="math display">\[
n-1 = (p-1) + (n-p).
\]</span></p>
<p>These match the sum of squares decomposition:</p>
<p><span class="math display">\[
\mathrm{SST} = \mathrm{SSR} + \mathrm{SSE}.
\]</span></p>
<div id="def-regression-mean-squares" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.2 (Regression and Error Mean Squares)</strong></span> A <strong>mean square</strong> is a sum of squares divided by its associated degrees of freedom. For a full-rank regression design with an intercept and <span class="math inline">\(1&lt;p&lt;n\)</span>, define</p>
<p><span class="math display">\[
\mathrm{MSR}=\frac{\mathrm{SSR}}{p-1},\qquad
\mathrm{MSE}=\frac{\mathrm{SSE}}{n-p}.
\]</span></p>
<p>Here <span class="math inline">\(p\)</span> includes the intercept coefficient.</p>
</div>
<p>Dividing by degrees of freedom accounts for the different dimensions contributing to each sum of squares. Under the linear-model moment assumptions from Chapter 3, MSE is an unbiased estimator of <span class="math inline">\(\sigma^2\)</span>. MSR estimates the same noise level under the overall null hypothesis, which motivates their ratio.</p>
</section>
<section id="the-overall-f-test" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="the-overall-f-test"><span class="header-section-number">4.2</span> The Overall F Test</h2>
<p>A major inferential question is whether the regression model provides any explanatory power beyond the intercept-only model. Suppose the model includes an intercept and <span class="math inline">\(p-1\)</span> additional predictors. The null hypothesis is</p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = \cdots = \beta_{p-1} = 0,
\]</span></p>
<p>where <span class="math inline">\(\beta_0\)</span> is the intercept and <span class="math inline">\(p\)</span> counts all regression coefficients. Equivalently, under <span class="math inline">\(H_0\)</span>, the mean response does not depend on the predictors. The alternative is that at least one non-intercept coefficient is nonzero.</p>
<div id="thm-overall-f" class="theorem">
<p><span class="theorem-title"><strong>Theorem 4.2 (Overall F Test)</strong></span> Under the normal linear model with a fixed, full-rank design containing an intercept and <span class="math inline">\(1&lt;p&lt;n\)</span>, the null hypothesis that all non-intercept coefficients are zero gives</p>
<p><span class="math display">\[
F=\frac{\mathrm{SSR}/(p-1)}{\mathrm{SSE}/(n-p)}
=\frac{\mathrm{MSR}}{\mathrm{MSE}}
\sim F_{p-1,n-p}.
\]</span></p>
<p>Large values provide evidence against the intercept-only mean model. Exact finite-sample inference requires the normal, common-variance error assumptions; the sum-of-squares identity alone does not supply this distribution.</p>
</div>
<p><strong>Interpretation of the Overall F Test</strong></p>
<p>The numerator measures explained variation per regression degree of freedom. The denominator measures unexplained variation per residual degree of freedom. So the <span class="math inline">\(F\)</span> statistic compares:</p>
<ul>
<li>how much signal the model explains;</li>
<li>how much noise remains in the residuals.</li>
</ul>
<p>If the predictors have no effect, then both quantities should be of similar size, and the ratio should not be unusually large. If the predictors explain substantial variation, then the numerator should be much larger than the denominator.</p>
<div id="exr-overall-f-question" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 4.3 (In Class: What Does an Overall Rejection Mean?)</strong></span> An intercept model with two predictors is fitted to <span class="math inline">\(n=25\)</span> observations using a full-rank design. Write the overall null hypothesis and the F reference degrees of freedom under the normal linear model. How does this joint test differ from the individual t tests? If it rejects, must both individual slope tests also reject?</p>
</div>
<div id="sol-overall-f-question" class="proof solution">
<p><span class="proof-title"><em>Solution 4.3</em>. </span>Here <span class="math inline">\(p=3\)</span>, so <span class="math inline">\(H_0:\beta_1=\beta_2=0\)</span> and the reference distribution is <span class="math inline">\(F_{2,22}\)</span>. Rejection gives evidence that the two slopes are not jointly zero. It does not show that both are nonzero, and it does not require either individual test to reject at the same level. Each individual t test asks whether one slope is zero while retaining the other predictor; the overall F test asks whether both slopes are jointly zero. These are different questions, especially when predictors are correlated.</p>
</div>
<p><strong>Relationship to the Intercept-Only Model</strong></p>
<p>The overall <span class="math inline">\(F\)</span> test compares two models:</p>
<ul>
<li>the reduced model: intercept only;</li>
<li>the full model: intercept plus predictors.</li>
</ul>
<p>Thus the ANOVA decomposition provides the basis for formal model comparison. This leads naturally to the idea of nested models.</p>
</section>
<section id="nested-models" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="nested-models"><span class="header-section-number">4.3</span> Nested Models</h2>
<div id="def-nested-linear-models" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.3 (Nested Linear Models)</strong></span> For the same response vector and observations, let the reduced and full models have mean spaces <span class="math inline">\(\mathcal C(\mathbf X_R)\)</span> and <span class="math inline">\(\mathcal C(\mathbf X_F)\)</span>. The models are <strong>nested</strong> when</p>
<p><span class="math display">\[
\mathcal C(\mathbf X_R)\subseteq\mathcal C(\mathbf X_F).
\]</span></p>
<p>Thus every mean vector allowed by the reduced model is also allowed by the full model. A strict comparison requires ranks <span class="math inline">\(p_R&lt;p_F\)</span>; adding columns that are linear combinations of existing columns does not enlarge the mean space.</p>
</div>
<div id="exm-nested-regression-models" class="theorem example">
<p><span class="theorem-title"><strong>Example 4.1 (Adding a Predictor)</strong></span> Consider the reduced model <span class="math inline">\(Y_i=\beta_0+\beta_1x_{i1}+\varepsilon_i\)</span> and the full model <span class="math inline">\(Y_i=\beta_0+\beta_1x_{i1}+\beta_2x_{i2}+\varepsilon_i\)</span>. Setting <span class="math inline">\(\beta_2=0\)</span> recovers the reduced model. If the <span class="math inline">\(x_2\)</span> column is not in the span of the intercept and <span class="math inline">\(x_1\)</span>, the full model adds one degree of freedom.</p>
</div>
<div id="def-extra-sum-of-squares" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.4 (Extra Sum of Squares)</strong></span> For nested models fitted by OLS to the same response and observations, define the <strong>extra sum of squares</strong> for the full model relative to the reduced model as</p>
<p><span class="math display">\[
\mathrm{SS}_{\mathrm{extra}}=\mathrm{SSE}_R-\mathrm{SSE}_F.
\]</span></p>
<p>Its associated degrees of freedom are <span class="math inline">\(p_F-p_R\)</span>, where <span class="math inline">\(p_R\)</span> and <span class="math inline">\(p_F\)</span> are the design-matrix ranks.</p>
</div>
<div id="exr-nested-sse-discussion" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 4.4 (In-Class Discussion: Can the Larger Model Fit Worse?)</strong></span> Why must <span class="math inline">\(\mathrm{SSE}_F\le\mathrm{SSE}_R\)</span> when nested models are fitted by OLS to the same observations? Must the inequality be strict whenever a genuinely new predictor direction is added?</p>
</div>
<div id="sol-nested-sse-discussion" class="proof solution">
<p><span class="proof-title"><em>Solution 4.4</em>. </span>Every fitted mean vector allowed by the reduced model is also available to the full model. Minimizing the same residual sum of squares over this larger set cannot give a larger minimum. Equality is possible even if the model space grows: for the observed response, the added directions may provide no further reduction in residual variation. Thus greater flexibility guarantees a weak improvement in training fit, not a strictly positive improvement or a useful predictor.</p>
</div>
<p>A positive extra sum of squares alone is not evidence against the reduced model: the F test scales that improvement by its degrees of freedom and the estimated noise variance.</p>
<div id="thm-partial-f" class="theorem">
<p><span class="theorem-title"><strong>Theorem 4.3 (Partial F Test for Nested Normal Linear Models)</strong></span> Fit both models to the <strong>same response and the same observations</strong>. Suppose their fixed design matrices have nested column spaces, with ranks <span class="math inline">\(p_R&lt;p_F&lt;n\)</span>, and the full model has independent <span class="math inline">\(N(0,\sigma^2)\)</span> errors. Under the null hypothesis that the mean belongs to the reduced model,</p>
<p><span class="math display">\[
F=\frac{(\mathrm{SSE}_R-\mathrm{SSE}_F)/(p_F-p_R)}{\mathrm{SSE}_F/(n-p_F)}
\sim F_{p_F-p_R,n-p_F}.
\]</span></p>
<p>Large values give evidence against the reduced mean model. The numerator measures improvement per added degree of freedom; the denominator estimates the unexplained variance under the full model.</p>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Compare the models, not just the printed p-values">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Compare the models, not just the printed p-values
</div>
</div>
<div class="callout-body-container callout-body">
<p>Different missing-value patterns can cause two R fits to use different observations. Construct a common analysis dataset before comparing them. For one added coefficient, the partial F statistic equals the square of its two-sided t-test statistic from the full model.</p>
</div>
</div>
<div id="exr-partial-f-short-calculation" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 4.5 (In Class: A Better Fit, but Enough Improvement?)</strong></span> Two nested models use the same <span class="math inline">\(n=30\)</span> observations. The reduced model has rank <span class="math inline">\(p_R=2\)</span> and <span class="math inline">\(\mathrm{SSE}_R=90\)</span>; the full model has rank <span class="math inline">\(p_F=4\)</span> and <span class="math inline">\(\mathrm{SSE}_F=78\)</span>. Compute the extra sum of squares, its degrees of freedom, the full-model MSE, and the partial F statistic. Does a reduction in SSE by itself justify rejecting the reduced model?</p>
</div>
<div id="sol-partial-f-short-calculation" class="proof solution">
<p><span class="proof-title"><em>Solution 4.5</em>. </span>The improvement is <span class="math inline">\(90-78=12\)</span> on <span class="math inline">\(4-2=2\)</span> degrees of freedom. The full-model MSE is <span class="math inline">\(78/(30-4)=3\)</span>, so <span class="math inline">\(F=(12/2)/3=2\)</span>. Under the normal-model null, compare this with <span class="math inline">\(F_{2,26}\)</span>; the upper-tail p-value is about <span class="math inline">\(0.156\)</span>. The improvement is insufficient for rejection at the 5% level. More flexibility always weakly reduces training SSE, including when the added coefficients are zero.</p>
</div>
<p><strong>Connection with General Linear Hypotheses</strong></p>
<p>Nested column-space models correspond to linear restrictions on the full-model coefficients. More generally, Chapter 3 allows a specified affine restriction of the form</p>
<p><span class="math display">\[
H_0: \mathbf{C}\boldsymbol{\beta} = \mathbf{d}.
\]</span></p>
<p>So the ANOVA comparison of nested models is another way of expressing the general <span class="math inline">\(F\)</span> test from Chapter 3. In practice, this is one of the most common uses of regression ANOVA tables.</p>
<div id="def-sequential-partial-sums-of-squares" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.5 (Sequential and Partial Sums of Squares)</strong></span> For a term in a specified regression model, both quantities are extra sums of squares from a nested comparison on the same observations:</p>
<ul>
<li><strong>Sequential sum of squares:</strong> the reduction in SSE when the term is added after the preceding terms in a specified order.</li>
<li><strong>Partial sum of squares:</strong> the increase in SSE when the specified term is removed from a full model while the other specified terms are retained.</li>
</ul>
</div>
<p>When predictors are correlated, sequential sums of squares can depend on their order. Partial sums of squares answer a comparison conditional on the terms retained in the reduced model. With interactions or rank deficiency, state the exact restriction and respect model hierarchy rather than relying only on a Type I, II, or III label.</p>
<div id="def-coefficient-of-determination" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.6 (Coefficient of Determination)</strong></span> For an OLS fit with an intercept and <span class="math inline">\(\mathrm{SST}&gt;0\)</span>, the <strong>coefficient of determination</strong> is</p>
<p><span class="math display">\[
R^2=\frac{\mathrm{SSR}}{\mathrm{SST}}
=1-\frac{\mathrm{SSE}}{\mathrm{SST}}.
\]</span></p>
</div>
<p>By the ANOVA decomposition, <span class="math inline">\(R^2\)</span> lies between 0 and 1 and measures the proportion of centered variation explained by the fitted model. If every observed response is identical, <span class="math inline">\(\mathrm{SST}=0\)</span> and this ratio is undefined.</p>
<p><strong>Interpretation of R Squared</strong></p>
<ul>
<li>If <span class="math inline">\(R^2\)</span> is close to 1, the model explains a large proportion of the variation in the response.</li>
<li>If <span class="math inline">\(R^2\)</span> is close to 0, the model explains little of the variation.</li>
</ul>
<p>However, <span class="math inline">\(R^2\)</span> alone does not guarantee that the model is appropriate. A high <span class="math inline">\(R^2\)</span> does not ensure that assumptions are satisfied, and a low <span class="math inline">\(R^2\)</span> does not necessarily imply the model is useless.</p>
<div id="def-adjusted-r-squared" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 4.7 (Adjusted Coefficient of Determination)</strong></span> For an OLS fit with an intercept, <span class="math inline">\(\mathrm{SST}&gt;0\)</span>, and design rank <span class="math inline">\(p&lt;n\)</span>, define the <strong>adjusted coefficient of determination</strong> as</p>
<p><span class="math display">\[
R^2_{\mathrm{adj}}
=1-\frac{\mathrm{SSE}/(n-p)}{\mathrm{SST}/(n-1)}.
\]</span></p>
</div>
<p>Ordinary <span class="math inline">\(R^2\)</span> cannot decrease when the model space is enlarged on the same data. Adjusted <span class="math inline">\(R^2\)</span> accounts for the loss of residual degrees of freedom and can decrease or become negative. It compares residual mean square with the sample variance of the response; it is not a literal proportion of explained variation or an estimate of out-of-sample predictive performance.</p>
<div id="exm-anova-by-hand" class="theorem example">
<p><span class="theorem-title"><strong>Example 4.2 (A Small ANOVA Calculation)</strong></span> For the column vectors <span class="math inline">\(\mathbf x=(0,1,2,3)\)</span> and <span class="math inline">\(\mathbf y=(1,3,3,5)\)</span>, the fitted line is <span class="math inline">\(\hat y=1.2+1.2x\)</span>. Therefore <span class="math inline">\(\hat{\mathbf y}=(1.2,2.4,3.6,4.8)\)</span>, <span class="math inline">\(\mathbf e=(-0.2,0.6,-0.6,0.2)\)</span>, and <span class="math inline">\(\bar y=3\)</span>.</p>
<p><span class="math display">\[
\begin{aligned}
\mathrm{SST}&amp;=(1-3)^2+(3-3)^2+(3-3)^2+(5-3)^2=8,\\
\mathrm{SSE}&amp;=(-0.2)^2+0.6^2+(-0.6)^2+0.2^2=0.8,\\
\mathrm{SSR}&amp;=\mathrm{SST}-\mathrm{SSE}=8-0.8=7.2.
\end{aligned}
\]</span></p>
<p>Here <span class="math inline">\(n=4\)</span> and <span class="math inline">\(p=2\)</span>, so the regression, residual, and total degrees of freedom are 1, 2, and 3, respectively.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: right;">Sum of squares</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">Mean square</th>
<th style="text-align: right;">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td style="text-align: right;">7.2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.2</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td>Error</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">8.0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>The model has <span class="math inline">\(R^2=7.2/8=0.9\)</span>, yet the F-test p-value is <span class="math inline">\(P(F_{1,2}\ge18)\approx0.0513\)</span>. With only two residual degrees of freedom, a high training <span class="math inline">\(R^2\)</span> does not automatically give evidence at the 5% significance level.</p>
</div>
<div id="exr-r-squared-versus-adjustment" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 4.6 (In Class: Can Two Fit Summaries Disagree?)</strong></span> For the same <span class="math inline">\(n=10\)</span> observations with <span class="math inline">\(\mathrm{SST}=100\)</span>, an intercept model has rank 2 and SSE 20. Adding a predictor whose column is linearly independent of the existing columns increases the rank to 3 and reduces SSE to 19. Compute <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> for both fits. Did the one-unit reduction in SSE improve both summaries? Why can relying on <span class="math inline">\(R^2\)</span> alone be misleading?</p>
</div>
<div id="sol-r-squared-versus-adjustment" class="proof solution">
<p><span class="proof-title"><em>Solution 4.6</em>. </span>Ordinary <span class="math inline">\(R^2\)</span> increases from <span class="math inline">\(1-20/100=0.80\)</span> to <span class="math inline">\(1-19/100=0.81\)</span>. Adjusted <span class="math inline">\(R^2\)</span> decreases from <span class="math inline">\(1-(20/8)/(100/9)=0.775\)</span> to <span class="math inline">\(1-(19/7)/(100/9)\approx0.756\)</span>. The extra predictor reduces SSE but increases residual mean square, from <span class="math inline">\(2.5\)</span> to about <span class="math inline">\(2.714\)</span>. Training <span class="math inline">\(R^2\)</span> cannot decrease when the model space grows, even when the new term only fits noise. A high <span class="math inline">\(R^2\)</span> also does not establish a correct mean function, appropriate error assumptions, or causality. Neither summary alone establishes better prediction on new observations.</p>
</div>
<p><strong>ANOVA Table Structure</strong></p>
<p>A standard regression ANOVA table has the following structure:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 18%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Sum of Squares</th>
<th>Degrees of Freedom</th>
<th>Mean Square</th>
<th>F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regression</td>
<td>SSR</td>
<td><span class="math inline">\(p-1\)</span></td>
<td>MSR</td>
<td>MSR/MSE</td>
</tr>
<tr class="even">
<td>Error</td>
<td>SSE</td>
<td><span class="math inline">\(n-p\)</span></td>
<td>MSE</td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>SST</td>
<td><span class="math inline">\(n-1\)</span></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Students should learn to move fluently between:</p>
<ul>
<li>formulas;</li>
<li>geometric interpretation;</li>
<li>software output.</li>
</ul>
</section>
<section id="r-demonstration" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="r-demonstration"><span class="header-section-number">4.4</span> R Demonstration</h2>
<p><strong>Fit a simple regression model</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x)

Residuals:
   1    2    3    4 
-0.2  0.6 -0.6  0.2 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)   1.2000     0.5292   2.268   0.1515  
x             1.2000     0.2828   4.243   0.0513 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6325 on 2 degrees of freedom
Multiple R-squared:    0.9, Adjusted R-squared:   0.85 
F-statistic:    18 on 1 and 2 DF,  p-value: 0.05132</code></pre>
</div>
</div>
<p><strong>Obtain the ANOVA table</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: y
          Df Sum Sq Mean Sq F value  Pr(&gt;F)  
x          1    7.2     7.2      18 0.05132 .
Residuals  2    0.8     0.4                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Verify sums of squares manually</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(y)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> <span class="fu">fitted</span>(fit)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">resid</span>(fit)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((y <span class="sc">-</span> ybar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>(e<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>SSR <span class="ot">&lt;-</span> <span class="fu">sum</span>((yhat <span class="sc">-</span> ybar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">SST =</span> SST, <span class="at">SSR =</span> SSR, <span class="at">SSE =</span> SSE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>SST SSR SSE 
8.0 7.2 0.8 </code></pre>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>SST <span class="sc">-</span> SSR <span class="sc">-</span> SSE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.330669e-16</code></pre>
</div>
</div>
<p><strong>See the three sources of variation.</strong> Each vertical segment below represents one deviation. Squaring and adding the four segment lengths gives the corresponding sum of squares.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">2.4</span>, <span class="fl">0.6</span>),</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">mgp =</span> <span class="fu">c</span>(<span class="fl">2.4</span>, <span class="fl">0.7</span>, <span class="dv">0</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (component <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"Total"</span>, <span class="st">"Explained"</span>, <span class="st">"Residual"</span>)) {</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(x, y, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">5.5</span>), <span class="at">xlab =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"y"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> component, <span class="at">cex.main =</span> <span class="dv">1</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> ybar, <span class="at">col =</span> <span class="st">"gray60"</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(fit, <span class="at">col =</span> <span class="st">"steelblue4"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (component <span class="sc">==</span> <span class="st">"Total"</span>) {</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">segments</span>(x, ybar, x, y, <span class="at">col =</span> <span class="st">"gray35"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (component <span class="sc">==</span> <span class="st">"Explained"</span>) {</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">segments</span>(x, ybar, x, yhat, <span class="at">col =</span> <span class="st">"steelblue4"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">points</span>(x, yhat, <span class="at">pch =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"steelblue4"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">segments</span>(x, yhat, x, y, <span class="at">col =</span> <span class="st">"darkorange3"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-anova-variation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anova-variation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_files/figure-html/fig-anova-variation-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anova-variation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Total deviations from the sample mean, explained deviations of fitted values from the mean, and residual deviations from the fitted line. SST = SSR + SSE holds after summing across observations; it is not a point-by-point identity between squared deviations.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Compute R squared manually</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> SSR <span class="sc">/</span> SST</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>R2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9</code></pre>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9</code></pre>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)<span class="sc">$</span>adj.r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.85</code></pre>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(<span class="dv">18</span>, <span class="at">df1 =</span> <span class="dv">1</span>, <span class="at">df2 =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0513167</code></pre>
</div>
</div>
<p><strong>Compare nested models</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">13</span>, <span class="dv">14</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x1 =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x2 =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">5</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>fit_reduced <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> dat)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>fit_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, <span class="at">data =</span> dat)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_reduced, fit_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ x1
Model 2: y ~ x1 + x2
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1      6 6.8214                           
2      5 4.6613  1    2.1601 2.3171 0.1884</code></pre>
</div>
</div>
<p><strong>Inspect the two fitted models</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_reduced)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.85714 -0.30357  0.03571  0.33036  1.60714 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.5357     0.8308   3.052 0.022453 *  
x1            1.4643     0.1645   8.900 0.000112 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.066 on 6 degrees of freedom
Multiple R-squared:  0.9296,    Adjusted R-squared:  0.9178 
F-statistic: 79.21 on 1 and 6 DF,  p-value: 0.0001121</code></pre>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_full)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2, data = dat)

Residuals:
      1       2       3       4       5       6       7       8 
 0.4032 -1.0403  0.3306  0.8871 -1.1371  0.4194  0.7903 -0.6532 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   2.9677     0.8041   3.691  0.01413 * 
x1            1.8387     0.2876   6.394  0.00139 **
x2           -0.6048     0.3973  -1.522  0.18845   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9655 on 5 degrees of freedom
Multiple R-squared:  0.9519,    Adjusted R-squared:  0.9326 
F-statistic: 49.46 on 2 and 5 DF,  p-value: 0.0005079</code></pre>
</div>
</div>
<p><strong>Interpretation of Software Output</strong></p>
<p>For a fitted model in R:</p>
<ul>
<li><code>anova(fit)</code> gives sequential sums of squares in the order terms enter a single model;</li>
<li><code>anova(fit_reduced, fit_full)</code> compares nested models;</li>
<li><code>summary(fit)</code> reports the overall <span class="math inline">\(F\)</span> statistic, <span class="math inline">\(R^2\)</span>, and adjusted <span class="math inline">\(R^2\)</span>.</li>
</ul>
<p>Students should understand that these outputs are not separate topics. They are all built from the same least squares geometry and distribution theory.</p>
<div id="exm-timber-volume" class="theorem example">
<p><span class="theorem-title"><strong>Example 4.3 (Optional Real-Data Example: Is Tree Height Useful Beyond Diameter?)</strong></span> Return to the forestry question. R’s <code>trees</code> data contain timber volume in cubic feet, height in feet, and a variable named <code>Girth</code> that is actually <strong>diameter in inches</strong>, measured 4 feet 6 inches above the ground. We rename it <code>Diameter</code> to avoid that labeling trap. Each row represents one of 31 felled black cherry trees. See the <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/trees.html">official dataset documentation</a> for the source and measurement definitions.</p>
<p><strong>State the question first.</strong> Comparing <span class="math inline">\(M_0\)</span> with <span class="math inline">\(M_2\)</span> asks whether diameter and height together improve on a constant mean. Comparing <span class="math inline">\(M_1\)</span> with <span class="math inline">\(M_2\)</span> asks whether height contributes after adjusting for diameter. For the second question, <span class="math inline">\(H_0:\beta_{\mathrm{Height}}=0\)</span>. These are distinct questions even though both use an F test.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="ot">&lt;-</span> datasets<span class="sc">::</span>trees</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>tree_dat<span class="sc">$</span>Diameter <span class="ot">&lt;-</span> tree_dat<span class="sc">$</span>Girth</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>tree_dat <span class="ot">&lt;-</span> tree_dat[, <span class="fu">c</span>(<span class="st">"Volume"</span>, <span class="st">"Diameter"</span>, <span class="st">"Height"</span>)]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">anyNA</span>(tree_dat))</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>fit_tree0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> tree_dat)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>fit_tree_d <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter, <span class="at">data =</span> tree_dat)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>fit_tree_dh <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter <span class="sc">+</span> Height, <span class="at">data =</span> tree_dat)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Constant mean"</span>, <span class="st">"Diameter"</span>, <span class="st">"Diameter + height"</span>),</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Rank =</span> <span class="fu">c</span>(fit_tree0<span class="sc">$</span>rank, fit_tree_d<span class="sc">$</span>rank, fit_tree_dh<span class="sc">$</span>rank),</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">SSE =</span> <span class="fu">c</span>(<span class="fu">deviance</span>(fit_tree0), <span class="fu">deviance</span>(fit_tree_d),</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>          <span class="fu">deviance</span>(fit_tree_dh))), <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Rank</th>
<th style="text-align: right;">SSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Constant mean</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8106.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diameter</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">524.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diameter + height</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">421.92</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_tree_d, fit_tree_dh)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Volume ~ Diameter
Model 2: Volume ~ Diameter + Height
  Res.Df    RSS Df Sum of Sq      F  Pr(&gt;F)  
1     29 524.30                              
2     28 421.92  1    102.38 6.7943 0.01449 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Read the comparison.</strong> The SSE drops from about <span class="math inline">\(524.30\)</span> to <span class="math inline">\(421.92\)</span>. The added term uses one degree of freedom, and the full model has <span class="math inline">\(31-3=28\)</span> residual degrees of freedom. Thus</p>
<p><span class="math display">\[
F=\frac{(524.30-421.92)/1}{421.92/28}\approx6.79,
\qquad p\approx0.0145.
\]</span></p>
<p>Under the stated normal, common-variance error model, this provides evidence against a zero height coefficient after accounting for diameter. It is not the overall test of both slopes.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>op <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">2.2</span>, <span class="fl">0.6</span>),</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">mgp =</span> <span class="fu">c</span>(<span class="fl">2.4</span>, <span class="fl">0.7</span>, <span class="dv">0</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>tree_models <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"Diameter only"</span> <span class="ot">=</span> fit_tree_d,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Diameter + height"</span> <span class="ot">=</span> fit_tree_dh)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>volume_limits <span class="ot">&lt;-</span> <span class="fu">range</span>(<span class="fu">c</span>(tree_dat<span class="sc">$</span>Volume, <span class="fu">fitted</span>(fit_tree_d),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">fitted</span>(fit_tree_dh)))</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (label <span class="cf">in</span> <span class="fu">names</span>(tree_models)) {</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  prediction <span class="ot">&lt;-</span> <span class="fu">fitted</span>(tree_models[[label]])</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(tree_dat<span class="sc">$</span>Diameter, tree_dat<span class="sc">$</span>Volume, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.65</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylim =</span> volume_limits, <span class="at">xlab =</span> <span class="st">"Diameter (inches)"</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Timber volume (cubic feet)"</span>, <span class="at">main =</span> label)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">segments</span>(tree_dat<span class="sc">$</span>Diameter, tree_dat<span class="sc">$</span>Volume,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>           tree_dat<span class="sc">$</span>Diameter, prediction, <span class="at">col =</span> <span class="st">"darkorange3"</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(tree_dat<span class="sc">$</span>Diameter, prediction, <span class="at">pch =</span> <span class="dv">1</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="st">"steelblue4"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="fu">c</span>(<span class="st">"Observed"</span>, <span class="st">"Fitted"</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>),</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"steelblue4"</span>), <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(op)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-tree-model-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tree-model-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="04_files/figure-html/fig-tree-model-comparison-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tree-model-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3: The same 31 trees under two mean models. Black dots are measured volumes; blue circles are fitted volumes. Orange segments show residuals. Adding height reduces the sum of squared residual lengths, but the F test asks whether that improvement is large relative to the estimated noise.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Check your understanding.</strong> Why use 28 rather than 29 in the variance estimate? What would change if some trees had missing heights? The denominator comes from the full model. With missing heights, first form one common dataset and refit both models on it; comparing fits on different observations confounds the added predictor with a changed sample.</p>
<p><strong>What this example does not settle.</strong> These are observational measurements, so the comparison is not a causal effect of making a tree taller. A statistically significant height term also does not decide whether measuring height is worth its cost or how much it helps predict new trees. Those decisions require practical error tolerances and validation. Inspect residuals and the mean function before using the raw-scale linear model operationally; transformations and model assessment appear later in the course.</p>
</div>
</section>
<section id="summary" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="summary"><span class="header-section-number">4.5</span> Summary</h2>
<p>In this chapter, we developed the ANOVA framework for linear regression. We defined:</p>
<p><span class="math display">\[
\mathrm{SST}, \qquad \mathrm{SSR}, \qquad \mathrm{SSE},
\]</span></p>
<p>and showed that, with an intercept,</p>
<p><span class="math display">\[
\mathrm{SST} = \mathrm{SSR} + \mathrm{SSE}.
\]</span></p>
<p>This decomposition led to:</p>
<ul>
<li>the ANOVA table;</li>
<li>the overall <span class="math inline">\(F\)</span> test for regression;</li>
<li>the comparison of nested models through extra sums of squares;</li>
<li>the interpretation of <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span>.</li>
</ul>
</section>
<section id="practice-problems" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="practice-problems"><span class="header-section-number">4.6</span> Practice Problems</h2>
<p><strong>Conceptual</strong></p>
<ol type="1">
<li>Explain the meaning of SST, SSR, and SSE in words.</li>
<li>Explain why the regression degrees of freedom are <span class="math inline">\(p-1\)</span> when the model includes an intercept.</li>
<li>Explain the difference between the overall <span class="math inline">\(F\)</span> test and a test for a single coefficient.</li>
</ol>
<p><strong>Computational</strong></p>
<p>Suppose a regression model with intercept has:</p>
<ul>
<li><span class="math inline">\(n=20\)</span>,</li>
<li><span class="math inline">\(p=4\)</span>,</li>
<li><span class="math inline">\(\mathrm{SST}=100\)</span>,</li>
<li><span class="math inline">\(\mathrm{SSE}=40\)</span>.</li>
</ul>
<p>Compute:</p>
<ol type="1">
<li><span class="math inline">\(\mathrm{SSR}\)</span>,</li>
<li>the degrees of freedom for regression and error,</li>
<li><span class="math inline">\(\mathrm{MSR}\)</span>,</li>
<li><span class="math inline">\(\mathrm{MSE}\)</span>,</li>
<li>the overall <span class="math inline">\(F\)</span> statistic,</li>
<li><span class="math inline">\(R^2\)</span>.</li>
</ol>
<p><strong>Nested Model Problem</strong></p>
<p>A reduced model has <span class="math inline">\(\mathrm{SSE}_R = 120\)</span> with <span class="math inline">\(p_R = 3\)</span>, and a full model has <span class="math inline">\(\mathrm{SSE}_F = 90\)</span> with <span class="math inline">\(p_F = 5\)</span>. If <span class="math inline">\(n=30\)</span>, compute the nested-model <span class="math inline">\(F\)</span> statistic.</p>
<p><strong>Suggested Homework</strong></p>
<p>Complete the following tasks:</p>
<ul>
<li>prove the decomposition <span class="math inline">\(\mathrm{SST}=\mathrm{SSR}+\mathrm{SSE}\)</span> when the model includes an intercept;</li>
<li>derive the overall <span class="math inline">\(F\)</span> statistic from the ANOVA decomposition;</li>
<li>fit a regression model in R and reproduce the ANOVA table by hand;</li>
<li>compare two nested models using an extra sum of squares test;</li>
<li>interpret both <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> for a chosen dataset.</li>
</ul>


</section>

</main> <!-- /main -->
<script>
  document.addEventListener("DOMContentLoaded", function () {
    
    document
    .querySelectorAll('div.solution.proof[id^="sol-"]')
    .forEach(function (solution) {
      
      // Get Quarto's automatically generated title,
      // e.g. "Solution 2.1"
      const proofTitle = solution.querySelector(".proof-title");

      let titleText = "Solution";

      if (proofTitle) {
        titleText = proofTitle.textContent
          .trim()
          .replace(/\.$/, "");

        // Remove the original inline title
        proofTitle.remove();
      }

      // Create collapsible <details>
      const details = document.createElement("details");
      details.className = "solution-collapse";

      // Keep the original ID so cross-references still work
      details.id = solution.id;

      const summary = document.createElement("summary");
      summary.textContent = titleText;

      const body = document.createElement("div");
      body.className = "solution-collapse-body";

      // Move the original solution contents into the collapsible body
      while (solution.firstChild) {
        body.appendChild(solution.firstChild);
      }

      // Remove an empty first paragraph if Quarto leaves one behind
      const firstParagraph = body.querySelector(":scope > p:first-child");

      if (
        firstParagraph &&
        firstParagraph.textContent.trim() === "" &&
        firstParagraph.children.length === 0
      ) {
        firstParagraph.remove();
      }

      details.appendChild(summary);
      details.appendChild(body);

      solution.replaceWith(details);
    });

});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_OLS_inference.html" class="pagination-link" aria-label="Distribution Theory of OLS and Inference">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Distribution Theory of OLS and Inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>