<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Multiple Regression and Categorical Predictors – STAT8561 - Linear Statistical Analysis I</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./App_F-quantile-regression.html" rel="next">
<link href="./04.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-de3257830c0d0a37460d18c755b5b021.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom-callouts.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STAT8561 - Linear Statistical Analysis I</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/chikuang/Teaching-Stat8561"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i>
<span class="menu-text"></span></a>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="././STAT8561---Linear-Statistical-Analysis-I.pdf"> <i class="bi bi-file-pdf" role="img" aria-label="Download PDF">
</i>
<span class="menu-text"></span></a>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multiple Regression and Categorical Predictors</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container">
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./01_matrix_representation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Matrix Representation and Notation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./02_LSE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Least Squares Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./03_OLS_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Distribution Theory of OLS and Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Model Comparison, Partial F Tests, and ANOVA</span></span></a>
  </div>
</li>
<li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./05.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multiple Regression and Categorical Predictors</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container">
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Optional topic</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a>
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./App_F-quantile-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quantile Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./App_G-mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mixed-Effects Models</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container">
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendix</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a>
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./App_A-matrix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Matrix Algebra Review</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./App_H-basic-mathematical-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic Mathematical Statistics</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container">
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Assessments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a>
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./Assignment1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container">
  <a href="./Assignment2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment 2</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>

  <ul>
  <li><a href="#sec-ch5-adjusted" id="toc-sec-ch5-adjusted" class="nav-link active" data-scroll-target="#sec-ch5-adjusted"><span class="header-section-number">5.1</span> Multiple regression and adjusted interpretation</a></li>
  <li><a href="#sec-ch5-factor-coding" id="toc-sec-ch5-factor-coding" class="nav-link" data-scroll-target="#sec-ch5-factor-coding"><span class="header-section-number">5.2</span> Categorical predictors are columns of a design matrix</a></li>
  <li><a href="#sec-ch5-additive" id="toc-sec-ch5-additive" class="nav-link" data-scroll-target="#sec-ch5-additive"><span class="header-section-number">5.3</span> A continuous predictor and a group indicator</a></li>
  <li><a href="#sec-ch5-interaction" id="toc-sec-ch5-interaction" class="nav-link" data-scroll-target="#sec-ch5-interaction"><span class="header-section-number">5.4</span> Interactions and conditional comparisons</a></li>
  <li><a href="#sec-ch5-comparisons" id="toc-sec-ch5-comparisons" class="nav-link" data-scroll-target="#sec-ch5-comparisons"><span class="header-section-number">5.5</span> Match the hypothesis to the model comparison</a></li>
  <li><a href="#sec-ch5-coding-checks" id="toc-sec-ch5-coding-checks" class="nav-link" data-scroll-target="#sec-ch5-coding-checks"><span class="header-section-number">5.6</span> Coding checks and the bridge to contrasts</a></li>
  <li><a href="#sec-ch5-practice" id="toc-sec-ch5-practice" class="nav-link" data-scroll-target="#sec-ch5-practice"><span class="header-section-number">5.7</span> Concept checks and practice</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-multiple-regression" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Multiple Regression and Categorical Predictors</span></span></h1>
</div>



<div class="quarto-title-meta">




  </div>



</header>


<p><a href="./04.html">Chapter 4</a> asked whether additional columns of a design matrix improve a model. This chapter asks what those columns mean. We connect a scientific comparison to a mean function, construct the corresponding design matrix, and interpret the fitted coefficients.</p>
<blockquote class="blockquote">
<p><strong>Learning Objectives</strong></p>
<p>By the end of this chapter, students should be able to:</p>
<ul>
<li>distinguish a marginal association from an adjusted association;</li>
<li>translate a factor into indicator columns and identify the reference group;</li>
<li>count model parameters and recognize redundant columns;</li>
<li>write group-specific mean functions for additive and interaction models;</li>
<li>explain how centering and reference coding change coefficient meanings;</li>
<li>match a scientific question to a nested-model comparison;</li>
<li>use <code>model.matrix()</code>, <code>lm()</code>, and predictions to check an interpretation.</li>
</ul>
</blockquote>
<p><strong>Reading.</strong> Read the sections on multiple regression, qualitative predictors, and interaction terms in Montgomery, Peck, and Vining <span class="citation" data-cites="montgomery:2021:book">(<a href="references.html#ref-montgomery:2021:book" role="doc-biblioref">Montgomery et al. 2021</a>)</span> and Seber and Lee <span class="citation" data-cites="seber:2003:book">(<a href="references.html#ref-seber:2003:book" role="doc-biblioref">Seber and Lee 2003</a>)</span>. The R examples use built-in datasets and require no additional data downloads.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Two class meetings, one modelling workflow">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Two class meetings, one modelling workflow
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the first meeting, focus on adjusted interpretation, indicator coding, and additive models. In the second, study interactions, centering, and the model comparisons that distinguish different scientific questions. Chapter 6 will develop contrasts and inference for selected comparisons in more detail.</p>
<p>Our workflow is <strong>question → mean function → design matrix → interpretation → comparison</strong>. The least squares and inference tools remain those from Chapters 2–4.</p>
</div>
</div>
<section id="sec-ch5-adjusted" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-ch5-adjusted"><span class="header-section-number">5.1</span> Multiple regression and adjusted interpretation</h2>
<p>For <span class="math inline">\(k\)</span> continuous predictors, an additive mean model is</p>
<p><span class="math display">\[
\mu(\mathbf x_i)=\mathbb E(Y_i\mid\mathbf x_i)
=\beta_0+\sum_{j=1}^{k}\beta_j x_{ij},
\qquad Y_i=\mu(\mathbf x_i)+\varepsilon_i.
\]</span></p>
<p>With an intercept and no redundant columns, <span class="math inline">\(p=k+1\)</span>. Throughout this course, <strong><span class="math inline">\(p\)</span> counts columns of the design matrix, including the intercept</strong>. A factor or an interaction can contribute several columns, so the number of named variables need not equal the number of parameters.</p>
<p>The design matrix is</p>
<p><span class="math display">\[
\mathbf X=
\begin{bmatrix}
1&amp;x_{11}&amp;\cdots&amp;x_{1k}\\
1&amp;x_{21}&amp;\cdots&amp;x_{2k}\\
\vdots&amp;\vdots&amp;&amp;\vdots\\
1&amp;x_{n1}&amp;\cdots&amp;x_{nk}
\end{bmatrix}.
\]</span></p>
<p>Full column rank gives the familiar estimator <span class="math inline">\((\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\mathbf Y\)</span>. Least squares itself does not require normal errors. For the exact <span class="math inline">\(t\)</span> and <span class="math inline">\(F\)</span> procedures in this chapter, we use the normal linear model from <a href="./03_OLS_inference.html">Chapter 3</a>: fixed full-rank <span class="math inline">\(\mathbf X\)</span> and independent <span class="math inline">\(N(0,\sigma^2)\)</span> errors.</p>
<div id="def-ch5-adjusted-coefficient" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 5.1 (Adjusted Regression Coefficient)</strong></span> In an additive linear mean model, <span class="math inline">\(\beta_j\)</span> is the difference in mean response associated with a one-unit increase in <span class="math inline">\(x_j\)</span>, <strong>holding the other predictors fixed</strong>:</p>
<p><span class="math display">\[
\mu(x_1,\ldots,x_j+1,\ldots,x_k)
-\mu(x_1,\ldots,x_j,\ldots,x_k)=\beta_j.
\]</span></p>
<p>The intercept is the mean response when <span class="math inline">\(x_1=\cdots=x_k=0\)</span>. It may describe a useful baseline, or a point outside the range supported by the data.</p>
</div>
<p><strong>Why an added predictor can change a coefficient.</strong> A simple regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(x_1\)</span> compares observations with different <span class="math inline">\(x_1\)</span> values while leaving their other characteristics unadjusted. A regression on both <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> describes the association with <span class="math inline">\(x_1\)</span> at fixed <span class="math inline">\(x_2\)</span>. If <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> vary together, these are different comparisons. Neither slope should be interpreted without naming its model.</p>
<div id="exm-ch5-tree-adjustment" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.1 (The Same Height Measurement, Two Comparisons)</strong></span> Return to the 31 black cherry trees from Chapter 4. <code>Volume</code> is timber volume in cubic feet, <code>Height</code> is height in feet, and R’s variable <code>Girth</code> actually records diameter in inches. Each row is one tree. We rename that variable <code>Diameter</code>. <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/trees.html">Dataset documentation</a>.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>ch5_trees <span class="ot">&lt;-</span> <span class="fu">transform</span>(datasets<span class="sc">::</span>trees, <span class="at">Diameter =</span> Girth)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>ch5_tree_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Height, <span class="at">data =</span> ch5_trees)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>ch5_tree_adjusted <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Height <span class="sc">+</span> Diameter, <span class="at">data =</span> ch5_trees)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Height alone"</span>, <span class="st">"Height adjusted for diameter"</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Height_coefficient =</span> <span class="fu">c</span>(<span class="fu">coef</span>(ch5_tree_simple)[<span class="st">"Height"</span>],</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">coef</span>(ch5_tree_adjusted)[<span class="st">"Height"</span>])),</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Model"</span>, <span class="st">"Height coefficient"</span>),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Height coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Height alone</td>
<td style="text-align: right;">1.543</td>
</tr>
<tr class="even">
<td style="text-align: left;">Height adjusted for diameter</td>
<td style="text-align: right;">0.339</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The unadjusted height coefficient is about <strong>1.543</strong> cubic feet per foot. The adjusted coefficient is about <strong>0.339</strong>: among trees of the same diameter, one additional foot of height is associated with 0.339 more cubic feet of fitted mean volume. The fitted multiple regression equation is</p>
<p><span class="math display">\[
\widehat{\mathrm{Volume}}
=-57.988+0.339\,\mathrm{Height}+4.708\,\mathrm{Diameter}.
\]</span></p>
<p>These slopes answer different questions. The multiple-regression height coefficient is also the coefficient tested when Chapter 4 compared the diameter-only model with the diameter-plus-height model.</p>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Adjustment, overlap, and causal interpretation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Adjustment, overlap, and causal interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Holding diameter fixed” describes a comparison in the mean model; it does not mean an experiment made the same tree taller. An adjusted association is not automatically causal. A causal interpretation needs a defensible design and additional assumptions.</p>
<p>Also inspect which predictor combinations occur. If two predictors nearly move together, the data provide little information about changing one while holding the other fixed. Exact linear dependence causes rank deficiency; strong but imperfect dependence can inflate coefficient uncertainty. Detailed diagnostics come later.</p>
</div>
</div>
<div id="exr-ch5-adjusted-interpretation" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.1 (In Class: Interpret 0.339)</strong></span> Which interpretation matches the adjusted height coefficient?</p>
<p>A. Increasing any tree’s height by one foot causes its volume to increase by 0.339 cubic feet.</p>
<p>B. At the same diameter, a one-foot height difference corresponds to a 0.339-cubic-foot difference in fitted mean volume.</p>
<p>C. Every tree one foot taller has exactly 0.339 more cubic feet of observed volume.</p>
</div>
<div id="sol-ch5-adjusted-interpretation" class="proof solution">
<p><span class="proof-title"><em>Solution 5.1</em>. </span><strong>B.</strong> The coefficient describes an adjusted mean association. It is neither an automatic causal effect nor an exact difference between individual responses.</p>
</div>
</section>
<section id="sec-ch5-factor-coding" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-ch5-factor-coding"><span class="header-section-number">5.2</span> Categorical predictors are columns of a design matrix</h2>
<p>A categorical variable records group membership. Its labels do not supply numerical distances. Coding three unordered groups as 1, 2, and 3 and fitting one slope would impose equally spaced means; that is a modelling restriction, not a neutral relabeling.</p>
<div id="def-ch5-treatment-coding" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 5.2 (Reference-Group Indicator Coding)</strong></span> For a factor with <span class="math inline">\(g\)</span> observed levels, choose one reference level. With an intercept, use <span class="math inline">\(g-1\)</span> indicators for the remaining levels. For levels A, B, and C with A as reference, let</p>
<p><span class="math display">\[
D_{Bi}=\mathbb 1\{G_i=\mathrm B\},\qquad
D_{Ci}=\mathbb 1\{G_i=\mathrm C\}.
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
\mathbb E(Y_i\mid G_i)=\beta_0+\beta_BD_{Bi}+\beta_CD_{Ci}.
\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: center;">Row of <span class="math inline">\(\mathbf X\)</span></th>
<th style="text-align: center;">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;"><span class="math inline">\((1\;0\;0)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;"><span class="math inline">\((1\;1\;0)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_0+\beta_B\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;"><span class="math inline">\((1\;0\;1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_0+\beta_C\)</span></td>
</tr>
</tbody>
</table>
<p>Thus <span class="math inline">\(\beta_B=\mu_B-\mu_A\)</span> and <span class="math inline">\(\beta_C=\mu_C-\mu_A\)</span>. A comparison of B with C is <span class="math inline">\(\beta_B-\beta_C\)</span>, not either coefficient alone.</p>
</div>
<p>For two observations from each group, ordered A, A, B, B, C, C,</p>
<p><span class="math display">\[
\mathbf X=
\begin{bmatrix}
1&amp;0&amp;0\\1&amp;0&amp;0\\1&amp;1&amp;0\\1&amp;1&amp;0\\1&amp;0&amp;1\\1&amp;0&amp;1
\end{bmatrix},\qquad p=3.
\]</span></p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ch5_groups <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>), <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>)))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(ch5_groups<span class="sc">$</span>group) <span class="ot">&lt;-</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">contr.treatment</span>(<span class="fu">levels</span>(ch5_groups<span class="sc">$</span>group), <span class="at">base =</span> <span class="dv">1</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">model.matrix</span>(<span class="sc">~</span> group, <span class="at">data =</span> ch5_groups),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">(Intercept)</th>
<th style="text-align: right;">groupB</th>
<th style="text-align: right;">groupC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Why not use all indicators with an intercept?</strong> For every observation,</p>
<p><span class="math display">\[
D_{Ai}+D_{Bi}+D_{Ci}=1.
\]</span></p>
<p>The intercept column is therefore the sum of the three indicator columns. Four written coefficients would represent only three independent columns. One alternative is to remove the intercept and use all three indicators:</p>
<p><span class="math display">\[
\mathbb E(Y_i\mid G_i)=\mu_AD_{Ai}+\mu_BD_{Bi}+\mu_CD_{Ci}.
\]</span></p>
<p>This <strong>cell-means parameterization</strong> describes the same set of mean vectors. In R it is <code>y ~ 0 + group</code>. Removing the intercept here does not force the group means to zero; the indicator columns already span the constant vector.</p>
<div id="exm-ch5-reference-change" class="theorem example">
<p><span class="theorem-title"><strong>Example 5.2 (Different Coefficients, the Same Group Means)</strong></span> Suppose the fitted means for A, B, and C are 18, 22, and 19.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Reference</th>
<th style="text-align: center;">Intercept</th>
<th style="text-align: center;">Other coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">B minus A: 4; C minus A: 1</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">A minus B: −4; C minus B: −3</td>
</tr>
</tbody>
</table>
<p>Changing the reference changes the coordinate system for the same fitted means. It does not change fitted values, residuals, SSE, or model rank. A coefficient test can nevertheless change because its named comparison has changed: B versus A is a different null hypothesis from C versus B.</p>
</div>
<div id="exr-ch5-rank" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.2 (In Class: Count Columns, Not Variable Names)</strong></span> A model contains an intercept, two continuous predictors, and one four-level factor using reference coding. Assume all columns are independent and <span class="math inline">\(n=40\)</span>.</p>
<ol type="1">
<li>How many regression parameters are there?</li>
<li>What are the residual degrees of freedom?</li>
<li>Would replacing the three factor indicators by all four indicators while retaining the intercept add an identifiable parameter?</li>
</ol>
</div>
<div id="sol-ch5-rank" class="proof solution">
<p><span class="proof-title"><em>Solution 5.2</em>. </span>There are <span class="math inline">\(p=1+2+3=6\)</span> parameters and <span class="math inline">\(40-6=34\)</span> residual degrees of freedom. <strong>No:</strong> all four indicators together with the intercept introduce a redundant column.</p>
</div>
</section>
<section id="sec-ch5-additive" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-ch5-additive"><span class="header-section-number">5.3</span> A continuous predictor and a group indicator</h2>
<p>We now follow one dataset through several models. R’s <code>ToothGrowth</code> data record an odontoblast-length response from 60 guinea pigs. The predictors are vitamin C dose (0.5, 1, or 2 mg/day) and delivery method: orange juice (<code>OJ</code>) or ascorbic acid (<code>VC</code>). Each row is one animal. <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/ToothGrowth.html">Dataset documentation</a>.</p>
<p><strong>Question.</strong> How does the mean response vary with dose, and is the OJ-minus-VC mean difference the same at every dose? We first describe fitted associations. The dataset documentation alone is not a complete account of randomization or of all conditions needed for a causal conclusion.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ch5_tooth <span class="ot">&lt;-</span> datasets<span class="sc">::</span>ToothGrowth</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ch5_tooth<span class="sc">$</span>supp <span class="ot">&lt;-</span> <span class="fu">factor</span>(ch5_tooth<span class="sc">$</span>supp, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"VC"</span>, <span class="st">"OJ"</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ch5_tooth<span class="sc">$</span>dose_c <span class="ot">&lt;-</span> ch5_tooth<span class="sc">$</span>dose <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>ch5_tooth<span class="sc">$</span>dose_f <span class="ot">&lt;-</span> <span class="fu">factor</span>(ch5_tooth<span class="sc">$</span>dose, <span class="at">levels =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(ch5_tooth<span class="sc">$</span>supp) <span class="ot">&lt;-</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">contr.treatment</span>(<span class="fu">levels</span>(ch5_tooth<span class="sc">$</span>supp), <span class="at">base =</span> <span class="dv">1</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(ch5_tooth<span class="sc">$</span>dose_f) <span class="ot">&lt;-</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">contr.treatment</span>(<span class="fu">levels</span>(ch5_tooth<span class="sc">$</span>dose_f), <span class="at">base =</span> <span class="dv">1</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">anyNA</span>(ch5_tooth))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>ch5_cell_summary <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  len <span class="sc">~</span> supp <span class="sc">+</span> dose, <span class="at">data =</span> ch5_tooth,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUN =</span> <span class="cf">function</span>(y) <span class="fu">c</span>(<span class="at">n =</span> <span class="fu">length</span>(y), <span class="at">mean =</span> <span class="fu">mean</span>(y)))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>ch5_summary_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ch5_cell_summary[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                                 ch5_cell_summary<span class="sc">$</span>len)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(ch5_summary_table, <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Method"</span>, <span class="st">"Dose (mg/day)"</span>, <span class="st">"n"</span>, <span class="st">"Mean length"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Dose (mg/day)</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean length</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">VC</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">OJ</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">13.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VC</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">16.77</td>
</tr>
<tr class="even">
<td style="text-align: left;">OJ</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">22.70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VC</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">26.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">OJ</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">26.06</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Both delivery methods are observed at each of the three doses, with 10 animals per combination. This gives overlap for comparing methods at those doses. It does not supply observations at every dose between them or outside the observed range.</p>
<div id="def-ch5-additive-model" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 5.3 (Additive Continuous-by-Group Model)</strong></span> Let <span class="math inline">\(x\)</span> be dose, <span class="math inline">\(x_c=x-1\)</span>, and <span class="math inline">\(z=\mathbb 1\{\mathrm{OJ}\}\)</span>. The additive model is</p>
<p><span class="math display">\[
\mu(x,z)=\beta_0+\beta_x x_c+\beta_g z.
\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Method</th>
<th style="text-align: center;">Mean function</th>
<th style="text-align: center;">Slope in dose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">VC (<span class="math inline">\(z=0\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(\beta_0+\beta_x(x-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_x\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">OJ (<span class="math inline">\(z=1\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(\beta_0+\beta_g+\beta_x(x-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_x\)</span></td>
</tr>
</tbody>
</table>
<p>The two lines are parallel, and <span class="math inline">\(\mu(x,1)-\mu(x,0)=\beta_g\)</span> at every dose. The intercept is the VC mean at <strong>1 mg/day</strong>, because that is where <span class="math inline">\(x_c=0\)</span>.</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>ch5_fit_add <span class="ot">&lt;-</span> <span class="fu">lm</span>(len <span class="sc">~</span> dose_c <span class="sc">+</span> supp, <span class="at">data =</span> ch5_tooth)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(ch5_fit_add))[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Estimate"</span>, <span class="st">"Standard error"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Standard error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">15.336</td>
<td style="text-align: right;">0.787</td>
</tr>
<tr class="even">
<td style="text-align: left;">dose_c</td>
<td style="text-align: right;">9.764</td>
<td style="text-align: right;">0.877</td>
</tr>
<tr class="odd">
<td style="text-align: left;">suppOJ</td>
<td style="text-align: right;">3.700</td>
<td style="text-align: right;">1.094</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The fitted equation is</p>
<p><span class="math display">\[
\widehat\mu(x,z)=15.336+9.764(x-1)+3.700z.
\]</span></p>
<p>At a fixed delivery method, a one-mg/day dose increase is associated with 9.764 more units of fitted mean length under this linear model. At a fixed dose, the fitted OJ mean exceeds the VC mean by 3.700 units. Neither statement says that every individual response follows its fitted mean exactly.</p>
<p><strong>Read the design matrix.</strong> There are three columns: intercept, centered dose, and the OJ indicator. The table below shows one row for each predictor combination; the full matrix repeats each combination for 10 animals.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ch5_profiles <span class="ot">&lt;-</span> <span class="fu">unique</span>(ch5_tooth[, <span class="fu">c</span>(<span class="st">"dose_c"</span>, <span class="st">"supp"</span>)])</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>ch5_profile_order <span class="ot">&lt;-</span> <span class="fu">order</span>(ch5_profiles<span class="sc">$</span>supp, ch5_profiles<span class="sc">$</span>dose_c)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>ch5_profiles <span class="ot">&lt;-</span> ch5_profiles[ch5_profile_order, ]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">model.matrix</span>(<span class="sc">~</span> dose_c <span class="sc">+</span> supp, <span class="at">data =</span> ch5_profiles),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">(Intercept)</th>
<th style="text-align: right;">dose_c</th>
<th style="text-align: right;">suppOJ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>With full rank, this model has <span class="math inline">\(p=3\)</span> and <span class="math inline">\(60-3=57\)</span> residual degrees of freedom. Using numeric dose imposes a straight-line mean within each method; treating the same three doses as a factor permits a separate mean at each dose. We will compare those assumptions below.</p>
</section>
<section id="sec-ch5-interaction" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-ch5-interaction"><span class="header-section-number">5.4</span> Interactions and conditional comparisons</h2>
<div id="def-ch5-interaction" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 5.4 (Continuous-by-Group Interaction)</strong></span> Add the product column <span class="math inline">\(x_cz\)</span>:</p>
<p><span class="math display">\[
\mu(x,z)=\beta_0+\beta_x x_c+\beta_gz+\beta_{xg}x_cz.
\]</span></p>
<p>The design row is <span class="math inline">\((1\;x_c\;z\;x_cz)\)</span>, so this two-group model has four parameters when full rank.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Method</th>
<th style="text-align: center;">Mean function</th>
<th style="text-align: center;">Slope in dose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">VC</td>
<td style="text-align: center;"><span class="math inline">\(\beta_0+\beta_x(x-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_x\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">OJ</td>
<td style="text-align: center;"><span class="math inline">\((\beta_0+\beta_g)+(\beta_x+\beta_{xg})(x-1)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\beta_x+\beta_{xg}\)</span></td>
</tr>
</tbody>
</table>
<p>The group difference at dose <span class="math inline">\(x\)</span> is</p>
<p><span class="math display">\[
\boxed{\Delta(x)=\mu(x,1)-\mu(x,0)=\beta_g+\beta_{xg}(x-1).}
\]</span></p>
<p>Thus <span class="math inline">\(\beta_g\)</span> is the group difference at 1 mg/day, and <span class="math inline">\(\beta_{xg}\)</span> is the OJ-minus-VC difference in slopes. An interaction means that one comparison depends on another predictor.</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>ch5_fit_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(len <span class="sc">~</span> dose_c <span class="sc">*</span> supp, <span class="at">data =</span> ch5_tooth)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(ch5_fit_int))[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Estimate"</span>, <span class="st">"Standard error"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Standard error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">15.011</td>
<td style="text-align: right;">0.772</td>
</tr>
<tr class="even">
<td style="text-align: left;">dose_c</td>
<td style="text-align: right;">11.716</td>
<td style="text-align: right;">1.195</td>
</tr>
<tr class="odd">
<td style="text-align: left;">suppOJ</td>
<td style="text-align: right;">4.351</td>
<td style="text-align: right;">1.091</td>
</tr>
<tr class="even">
<td style="text-align: left;">dose_c:suppOJ</td>
<td style="text-align: right;">-3.904</td>
<td style="text-align: right;">1.691</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>R expands <code>dose_c * supp</code> into <code>dose_c + supp + dose_c:supp</code>; <code>:</code> denotes the interaction term. See the <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/formula.html">R formula documentation</a>. The fitted equation is</p>
<p><span class="math display">\[
\widehat\mu(x,z)=15.011+11.716(x-1)+4.351z-3.904(x-1)z.
\]</span></p>
<p>The VC slope is about 11.716, and the OJ slope is <span class="math inline">\(\hat\beta_x+\hat\beta_{xg}\approx7.811\)</span>, using the unrounded estimates. The OJ-minus-VC difference is about 4.351 at 1 mg/day and 0.446 at 2 mg/day. A negative interaction coefficient means that the group difference decreases as dose increases; it does not mean that the OJ dose slope is negative.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ch5-parallel-versus-interaction" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two panels show length against vitamin C dose for VC and OJ. The additive fit has parallel lines; the interaction fit has a steeper VC line. Both panels display the same individual observations.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch5-parallel-versus-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05_files/figure-html/fig-ch5-parallel-versus-interaction-1.png" class="img-fluid figure-img" alt="Two panels show length against vitamin C dose for VC and OJ. The additive fit has parallel lines; the interaction fit has a steeper VC line. Both panels display the same individual observations." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch5-parallel-versus-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Additive and interaction fits to the same observations. Horizontal jitter separates overlapping points for display only; both models use the original doses. The additive model imposes parallel lines. The interaction model permits different slopes, while still requiring each method’s mean to be linear in dose.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Centering changes the baseline, not the fitted model.</strong> Start with the uncentered expression <span class="math inline">\(b_0+b_xx+b_gz+b_{xg}xz\)</span>. Substitute <span class="math inline">\(x=x_c+c\)</span> to obtain</p>
<p><span class="math display">\[
(b_0+cb_x)+b_xx_c+(b_g+cb_{xg})z+b_{xg}x_cz.
\]</span></p>
<p>Centering at <span class="math inline">\(c\)</span> changes the intercept to the reference-group mean at <span class="math inline">\(c\)</span> and the group coefficient to the difference at <span class="math inline">\(c\)</span>. The group-specific slopes, fitted means, residuals, and SSE stay the same when all the corresponding terms are retained.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ch5_fit_uncentered <span class="ot">&lt;-</span> <span class="fu">lm</span>(len <span class="sc">~</span> dose <span class="sc">*</span> supp, <span class="at">data =</span> ch5_tooth)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Parameterization =</span> <span class="fu">c</span>(<span class="st">"Raw dose (baseline: 0)"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Centered dose (baseline: 1)"</span>),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Group_coefficient =</span> <span class="fu">c</span>(<span class="fu">coef</span>(ch5_fit_uncentered)[<span class="st">"suppOJ"</span>],</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">coef</span>(ch5_fit_int)[<span class="st">"suppOJ"</span>])), <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Parameterization"</span>, <span class="st">"OJ coefficient"</span>),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Parameterization</th>
<th style="text-align: right;">OJ coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Raw dose (baseline: 0)</td>
<td style="text-align: right;">8.255</td>
</tr>
<tr class="even">
<td style="text-align: left;">Centered dose (baseline: 1)</td>
<td style="text-align: right;">4.351</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">isTRUE</span>(<span class="fu">all.equal</span>(<span class="fu">unname</span>(<span class="fu">fitted</span>(ch5_fit_uncentered)),</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">unname</span>(<span class="fu">fitted</span>(ch5_fit_int)))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Zero dose was not observed. Centering at an observed dose gives the group coefficient a more directly supported meaning. It does not establish linearity or create additional observations.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Keep the lower-order terms when interpreting an interaction">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Keep the lower-order terms when interpreting an interaction
</div>
</div>
<div class="callout-body-container callout-body">
<p>A model such as <code>dose_c * supp</code> includes both main effects and their interaction. Do not remove a main effect merely because its coefficient has a large p-value in the interaction model. That coefficient concerns a particular baseline, and dropping it imposes a constraint that can depend on the choice of center or reference group. Start with the scientific restriction you intend to test.</p>
</div>
</div>
<p><strong>Other interactions.</strong> For two continuous predictors, <span class="math inline">\(\mu=\beta_0+\beta_1x_1+\beta_2x_2+\beta_{12}x_1x_2\)</span> has slope <span class="math inline">\(\beta_1+\beta_{12}x_2\)</span> in <span class="math inline">\(x_1\)</span>. For two factors with <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> levels and all cells observed, reference coding uses <span class="math inline">\((a-1)(b-1)\)</span> interaction columns. With all main effects, there are <span class="math inline">\(1+(a-1)+(b-1)+(a-1)(b-1)=ab\)</span> parameters, one mean per cell. The same principle applies: a comparison varies with another predictor.</p>
<div id="exr-ch5-interaction-interpretation" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.3 (In Class: Which Difference Is Six?)</strong></span> Suppose <span class="math inline">\(x_c=x-1\)</span> and <span class="math inline">\(\widehat\mu=10+2x_c+6z-x_cz\)</span>.</p>
<ol type="1">
<li>What is the slope for <span class="math inline">\(z=1\)</span>?</li>
<li>At which original <span class="math inline">\(x\)</span> value is the group difference 6?</li>
<li>What is the group difference at <span class="math inline">\(x=3\)</span>?</li>
</ol>
</div>
<div id="sol-ch5-interaction-interpretation" class="proof solution">
<p><span class="proof-title"><em>Solution 5.3</em>. </span>The slope for <span class="math inline">\(z=1\)</span> is <span class="math inline">\(2-1=1\)</span>. The group difference is 6 at <span class="math inline">\(x=1\)</span>, where <span class="math inline">\(x_c=0\)</span>. At <span class="math inline">\(x=3\)</span>, <span class="math inline">\(x_c=2\)</span> and the difference is <span class="math inline">\(6-2=4\)</span>.</p>
</div>
</section>
<section id="sec-ch5-comparisons" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-ch5-comparisons"><span class="header-section-number">5.5</span> Match the hypothesis to the model comparison</h2>
<p>The <a href="./04.html#thm-partial-f">partial F test from Chapter 4</a> compares nested mean spaces on the <strong>same observations</strong>:</p>
<p><span class="math display">\[
F=\frac{(\mathrm{SSE}_R-\mathrm{SSE}_F)/(p_F-p_R)}
        {\mathrm{SSE}_F/(n-p_F)}.
\]</span></p>
<p>Under the reduced model and the stated normal, constant-variance error assumptions, the reference distribution is <span class="math inline">\(F_{p_F-p_R,n-p_F}\)</span>. These comparisons answer different questions:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Reduced model</th>
<th>Full model</th>
<th style="text-align: center;">Numerator df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Are the dose slopes equal?</td>
<td><code>dose_c + supp</code></td>
<td><code>dose_c * supp</code></td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td>Are the two entire dose lines identical?</td>
<td><code>dose_c</code></td>
<td><code>dose_c * supp</code></td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td>Is a straight line within each method adequate at the observed doses?</td>
<td><code>dose_c * supp</code></td>
<td><code>dose_f * supp</code></td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
<p><strong>Equal slopes.</strong> The additive model sets <span class="math inline">\(\beta_{xg}=0\)</span>. Comparing it with the interaction model tests whether the OJ-minus-VC difference is constant across dose under the two-line framework.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ch5_fit_add, ch5_fit_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: len ~ dose_c + supp
Model 2: len ~ dose_c * supp
  Res.Df     RSS Df Sum of Sq      F  Pr(&gt;F)
1     57 1022.56
2     56  933.63  1     88.92 5.3335 0.02463 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The comparison has 1 numerator and 56 denominator degrees of freedom, with <span class="math inline">\(F\approx5.334\)</span> and <span class="math inline">\(p\approx0.0246\)</span>. Under the model assumptions, this is evidence against equal slopes. It is not a test that the two groups have identical means at every dose.</p>
<p><strong>Identical lines.</strong> For the two lines to coincide, both <span class="math inline">\(\beta_g=0\)</span> and <span class="math inline">\(\beta_{xg}=0\)</span> must hold. A single p-value for <code>suppOJ</code> tests only the difference at the centering dose. Test the two restrictions together instead:</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ch5_fit_dose <span class="ot">&lt;-</span> <span class="fu">lm</span>(len <span class="sc">~</span> dose_c, <span class="at">data =</span> ch5_tooth)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ch5_fit_dose, ch5_fit_int)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: len ~ dose_c
Model 2: len ~ dose_c * supp
  Res.Df     RSS Df Sum of Sq      F   Pr(&gt;F)
1     58 1227.91
2     56  933.63  2    294.27 8.8253 0.000466 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Check the straight-line restriction.</strong> Dose takes three numerical values; the two-line model constrains each group’s three fitted means to lie on a line. A factor-dose-by-method model estimates all six cell means:</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>ch5_fit_cells <span class="ot">&lt;-</span> <span class="fu">lm</span>(len <span class="sc">~</span> dose_f <span class="sc">*</span> supp, <span class="at">data =</span> ch5_tooth)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ch5_fits <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">Additive =</span> ch5_fit_add, <span class="at">Interaction =</span> ch5_fit_int,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                 <span class="st">`</span><span class="at">Six cell means</span><span class="st">`</span> <span class="ot">=</span> ch5_fit_cells)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">names</span>(ch5_fits),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">p =</span> <span class="fu">vapply</span>(ch5_fits, <span class="cf">function</span>(fit) fit<span class="sc">$</span>rank, <span class="fu">numeric</span>(<span class="dv">1</span>)),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Residual_df =</span> <span class="fu">vapply</span>(ch5_fits, df.residual, <span class="fu">numeric</span>(<span class="dv">1</span>)),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">SSE =</span> <span class="fu">vapply</span>(ch5_fits, deviance, <span class="fu">numeric</span>(<span class="dv">1</span>))),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Model"</span>, <span class="st">"p"</span>, <span class="st">"Residual df"</span>, <span class="st">"SSE"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">Residual df</th>
<th style="text-align: right;">SSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Additive</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">1022.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interaction</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">933.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Six cell means</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">712.11</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(ch5_fit_int, ch5_fit_cells)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: len ~ dose_c * supp
Model 2: len ~ dose_f * supp
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)
1     56 933.63
2     54 712.11  2    221.53 8.3994 0.0006667 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The six-cell model has <span class="math inline">\(p=6\)</span> and 54 residual degrees of freedom. The comparison adds two independent directions, one departure from a straight line for each method’s three means. Here <span class="math inline">\(F\approx8.399\)</span> and <span class="math inline">\(p\approx0.000667\)</span> provide evidence against the straight-line restriction under the common-variance normal model. The fitted lines were useful for learning coefficient interpretation; this check shows why their shape should not be accepted automatically for these data.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ch5-dose-shape" class="quarto-float quarto-figure quarto-figure-center anchored" alt="For each delivery method, three cell means are plotted against dose and compared with its fitted straight line. The means at 1 mg/day lie above the fitted lines.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ch5-dose-shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05_files/figure-html/fig-ch5-dose-shape-1.png" class="img-fluid figure-img" alt="For each delivery method, three cell means are plotted against dose and compared with its fitted straight line. The means at 1 mg/day lie above the fitted lines." width="624">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ch5-dose-shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Cell means and the two-line fit. Points are the observed mean responses at each method-dose combination. The six-cell model reproduces these means; the straight lines impose additional restrictions. No observations outside 0.5–2 mg/day are shown.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="A factor is a block of columns">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A factor is a block of columns
</div>
</div>
<div class="callout-body-container callout-body">
<p>The three-level <code>dose_f</code> main effect uses two columns. The <code>dose_f:supp</code> interaction uses two more. A scientific test concerning an entire factor or interaction may therefore require a joint test, rather than selecting one printed coefficient p-value. Always count independent restrictions and use the full model’s residual degrees of freedom.</p>
</div>
</div>
</section>
<section id="sec-ch5-coding-checks" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-ch5-coding-checks"><span class="header-section-number">5.6</span> Coding checks and the bridge to contrasts</h2>
<p>R’s <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/model.matrix.html"><code>model.matrix()</code></a> reveals the columns created by a formula. Use it to connect the software coefficients to your written mean model.</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">model.matrix</span>(<span class="sc">~</span> dose_c <span class="sc">*</span> supp, <span class="at">data =</span> ch5_profiles),</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">(Intercept)</th>
<th style="text-align: right;">dose_c</th>
<th style="text-align: right;">suppOJ</th>
<th style="text-align: right;">dose_c:suppOJ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The last column is the product of centered dose and the OJ indicator. It is zero for every VC observation; it changes the OJ slope relative to VC.</p>
<p><strong>Verify a reference change.</strong> Refit with OJ as the reference while retaining the same model terms and observations:</p>
<div class="cell">
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ch5_relevel <span class="ot">&lt;-</span> ch5_tooth</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ch5_relevel<span class="sc">$</span>supp <span class="ot">&lt;-</span> <span class="fu">relevel</span>(ch5_relevel<span class="sc">$</span>supp, <span class="at">ref =</span> <span class="st">"OJ"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(ch5_relevel<span class="sc">$</span>supp) <span class="ot">&lt;-</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">contr.treatment</span>(<span class="fu">levels</span>(ch5_relevel<span class="sc">$</span>supp), <span class="at">base =</span> <span class="dv">1</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>ch5_fit_ojref <span class="ot">&lt;-</span> <span class="fu">lm</span>(len <span class="sc">~</span> dose_c <span class="sc">*</span> supp, <span class="at">data =</span> ch5_relevel)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Reference =</span> <span class="fu">c</span>(<span class="st">"VC"</span>, <span class="st">"OJ"</span>),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Intercept =</span> <span class="fu">c</span>(<span class="fu">coef</span>(ch5_fit_int)[<span class="dv">1</span>], <span class="fu">coef</span>(ch5_fit_ojref)[<span class="dv">1</span>]),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Dose_slope =</span> <span class="fu">c</span>(<span class="fu">coef</span>(ch5_fit_int)[<span class="dv">2</span>], <span class="fu">coef</span>(ch5_fit_ojref)[<span class="dv">2</span>]),</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">SSE =</span> <span class="fu">c</span>(<span class="fu">deviance</span>(ch5_fit_int), <span class="fu">deviance</span>(ch5_fit_ojref))),</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Reference</th>
<th style="text-align: right;">Intercept</th>
<th style="text-align: right;">Dose_slope</th>
<th style="text-align: right;">SSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">VC</td>
<td style="text-align: right;">15.011</td>
<td style="text-align: right;">11.716</td>
<td style="text-align: right;">933.635</td>
</tr>
<tr class="even">
<td style="text-align: left;">OJ</td>
<td style="text-align: right;">19.361</td>
<td style="text-align: right;">7.811</td>
<td style="text-align: right;">933.635</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Show R code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">isTRUE</span>(<span class="fu">all.equal</span>(<span class="fu">unname</span>(<span class="fu">fitted</span>(ch5_fit_int)),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">unname</span>(<span class="fu">fitted</span>(ch5_fit_ojref)))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The intercept now describes OJ at 1 mg/day, and the dose coefficient is the OJ slope. The fitted values and SSE agree with the VC-reference fit because the two design matrices span the same column space.</p>
<p><strong>Express a comparison before calculating it.</strong> In the VC-reference interaction model, order the coefficient vector as <span class="math inline">\((\beta_0,\beta_x,\beta_g,\beta_{xg})\)</span>. The OJ-minus-VC comparison at dose <span class="math inline">\(x_0\)</span> is</p>
<p><span class="math display">\[
\Delta(x_0)=\boldsymbol\ell^\top\boldsymbol\beta,
\qquad \boldsymbol\ell=(0,0,1,x_0-1).
\]</span></p>
<p>Here the comma-separated tuple denotes a column vector, as in Chapter 4. At <span class="math inline">\(x_0=1\)</span>, the comparison is <span class="math inline">\(\beta_g\)</span>; at <span class="math inline">\(x_0=2\)</span>, it is <span class="math inline">\(\beta_g+\beta_{xg}\)</span>. The linear-combination machinery from Chapter 3 therefore applies. Its standard error uses the full coefficient covariance matrix, including the covariance between the group and interaction estimates. Chapter 6 develops these comparisons, coding invariance, and the distinction between one comparison and a family of comparisons.</p>
</section>
<section id="sec-ch5-practice" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-ch5-practice"><span class="header-section-number">5.7</span> Concept checks and practice</h2>
<div id="exr-ch5-concept-checks" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.4 (Concept Check: Choose or Mark True/False)</strong></span> &nbsp;</p>
<ol type="1">
<li><strong>T/F.</strong> A multiple-regression coefficient always has the same interpretation as the slope in a simple regression using that predictor alone.</li>
<li><strong>Multiple choice.</strong> With an intercept, a three-level factor normally contributes <strong>(A)</strong> one, <strong>(B)</strong> two, or <strong>(C)</strong> three independent indicator columns.</li>
<li><strong>T/F.</strong> Reversing the reference category, while preserving the same model space, changes fitted values and SSE.</li>
<li><strong>Multiple choice.</strong> In a binary-group interaction model centered at <span class="math inline">\(x=1\)</span>, the group coefficient compares the groups <strong>(A)</strong> at every <span class="math inline">\(x\)</span>, <strong>(B)</strong> at <span class="math inline">\(x=0\)</span>, or <strong>(C)</strong> at <span class="math inline">\(x=1\)</span>.</li>
<li><strong>T/F.</strong> A negative interaction coefficient implies a negative slope in the non-reference group.</li>
<li><strong>Multiple choice.</strong> Testing identical lines requires <strong>(A)</strong> the interaction coefficient alone, <strong>(B)</strong> the group and interaction coefficients jointly, or <strong>(C)</strong> the intercept alone to be zero.</li>
<li><strong>T/F.</strong> Replacing numeric dose by a three-level factor merely renames the coefficients and must preserve the fitted means.</li>
<li><strong>T/F.</strong> Failing to reject equal slopes proves that the two population slopes are exactly equal.</li>
</ol>
</div>
<div id="sol-ch5-concept-checks" class="proof solution">
<p><span class="proof-title"><em>Solution 5.4</em>. </span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 84%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Item</th>
<th style="text-align: center;">Answer</th>
<th>Reason</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">F</td>
<td>Adjustment changes the comparison.</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">B</td>
<td>One level serves as the reference.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">F</td>
<td>The fitted mean space is unchanged.</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">C</td>
<td>The group coefficient is evaluated at centered dose zero.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">F</td>
<td>Add the interaction coefficient to the reference-group slope.</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">B</td>
<td>Both intercept difference and slope difference must vanish.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">F</td>
<td>A factor can relax the straight-line restriction.</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">F</td>
<td>Non-rejection is not proof of equality.</td>
</tr>
</tbody>
</table>
</div>
<div id="exr-ch5-model-comparison-practice" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.5 (Practice: State the Restrictions and Degrees of Freedom)</strong></span> Consider <span class="math inline">\(n=48\)</span> observations, a binary group <span class="math inline">\(z\)</span>, and a continuous predictor <span class="math inline">\(x\)</span>. Assume the relevant design matrices have full rank and the normal-model assumptions hold. The full model is <span class="math inline">\(\mu=\beta_0+\beta_xx+\beta_gz+\beta_{xg}xz\)</span>.</p>
<ol type="1">
<li>Write the null hypothesis for parallel lines and give both F degrees of freedom.</li>
<li>Write the null hypothesis for identical lines and give both F degrees of freedom.</li>
<li>Express the group difference at <span class="math inline">\(x=2\)</span> as a linear combination of coefficients.</li>
<li>If the full model has SSE 440 and the additive model has SSE 500, compute the partial F statistic for equal slopes.</li>
</ol>
</div>
<div id="sol-ch5-model-comparison-practice" class="proof solution">
<p><span class="proof-title"><em>Solution 5.5</em>. </span></p>
<ol type="1">
<li><span class="math inline">\(H_0:\beta_{xg}=0\)</span>; degrees of freedom <span class="math inline">\((1,44)\)</span>.</li>
<li><span class="math inline">\(H_0:\beta_g=\beta_{xg}=0\)</span>; degrees of freedom <span class="math inline">\((2,44)\)</span>.</li>
<li><span class="math inline">\(\Delta(2)=\beta_g+2\beta_{xg}\)</span>, with column vector <span class="math inline">\(\boldsymbol\ell=(0,0,1,2)\)</span> in the displayed coefficient order.</li>
<li><span class="math inline">\(F=\{(500-440)/1\}/(440/44)=6\)</span>.</li>
</ol>
</div>
<p><strong>Summary.</strong> The model’s columns determine what its coefficients mean. An additive slope is an adjusted mean comparison; factor coefficients depend on a reference group; an interaction makes a comparison depend on another predictor. Centering and releveling preserve fitted values when they only reparameterize the same mean space. Changing the mean space, such as relaxing a straight-line restriction, is a substantive modelling decision that can be assessed with the nested-model tools from Chapter 4.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-montgomery:2021:book" class="csl-entry" role="listitem">
Montgomery, Douglas C, Elizabeth A Peck, and G Geoffrey Vining. 2021. <em>Introduction to Linear Regression Analysis</em>. John Wiley &amp; Sons.
</div>
<div id="ref-seber:2003:book" class="csl-entry" role="listitem">
Seber, George AF, and Alan J Lee. 2003. <em>Linear Regression Analysis</em>. John Wiley &amp; Sons.
</div>
</div>
</section>

</main> <!-- /main -->
<script>
  document.addEventListener("DOMContentLoaded", function () {

    document
    .querySelectorAll('div.solution.proof[id^="sol-"]')
    .forEach(function (solution) {

      // Get Quarto's automatically generated title,
      // e.g. "Solution 2.1"
      const proofTitle = solution.querySelector(".proof-title");

      let titleText = "Solution";

      if (proofTitle) {
        titleText = proofTitle.textContent
          .trim()
          .replace(/\.$/, "");

        // Remove the original inline title
        proofTitle.remove();
      }

      // Create collapsible <details>
      const details = document.createElement("details");
      details.className = "solution-collapse";

      // Keep the original ID so cross-references still work
      details.id = solution.id;

      const summary = document.createElement("summary");
      summary.textContent = titleText;

      const body = document.createElement("div");
      body.className = "solution-collapse-body";

      // Move the original solution contents into the collapsible body
      while (solution.firstChild) {
        body.appendChild(solution.firstChild);
      }

      // Remove an empty first paragraph if Quarto leaves one behind
      const firstParagraph = body.querySelector(":scope > p:first-child");

      if (
        firstParagraph &&
        firstParagraph.textContent.trim() === "" &&
        firstParagraph.children.length === 0
      ) {
        firstParagraph.remove();
      }

      details.appendChild(summary);
      details.appendChild(body);

      solution.replaceWith(details);
    });

});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04.html" class="pagination-link" aria-label="Model Comparison, Partial F Tests, and ANOVA">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Model Comparison, Partial F Tests, and ANOVA</span></span>
      </a>
  </div>
  <div class="nav-page nav-page-next">
      <a href="./App_F-quantile-regression.html" class="pagination-link" aria-label="Quantile Regression"><span class="nav-page-text">Quantile Regression</span> <i class="bi bi-arrow-right-short"></i></a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>
