---
title: "Stat 230"
subtitle: |
  | Introduction to Probability
  | Winter 2024
author: |
  | Chi-Kuang Yeh
  | University of Waterloo
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "dark"
    downcute_theme: "chao"
    highlight: kate
    code_folding: hide
    number_sections: false
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Purpose of this page
The purpose of this page is to hold some of the additional materials provided by myself. Students should consult UW [Learn](https://api-4ccc589b.duosecurity.com/frame/v4/preauth/healthcheck?sid=frameless-c0657e9d-cb86-4ac9-a6a7-fd054ae21fd5) system.

# Course description
This course provides an introduction to probability models including sample spaces, mutually exclusive and independent events, conditional probability and Bayes' Theorem. The named distributions (Discrete Uniform, Hypergeometric, Binomial, Negative Binomial, Geometric, Poisson, Continuous Uniform, Exponential, Normal (Gaussian), and Multinomial) are used to model real phenomena. Discrete and continuous univariate random variables and their distributions are discussed. Joint probability functions, marginal probability functions, and conditional probability functions of two or more discrete random variables and functions of random variables are also discussed. Students learn how to calculate and interpret means, variances and covariances particularly for the named distributions. The Central Limit Theorem is used to approximate probabilities.

## Instructor
Chi-Kuang Yeh, I am a postdoc at the *Department of Statistics and Actuarial Science*.

+ Office: M3--3102 Desk 10. I will hold office hour in another location.
+ Email: [chi-kuang.yeh@uwaterloo.ca](mailto:chi-kuang.yeh@uwaterloo.ca)

## Course Coordinator
Dr. [Erik Hintz](https://uwaterloo.ca/scholar/ehintz). 

+ Office: M3--2106
+ Email: [erik.hintz@uuwaterloo.ca](mailto:erik.hintz@uwaterloo.ca)

## Logistic Issue
Contact Divya Lala

+ Email: [divya.lala@uwaterloo.ca](mailto:divya.lala@uwaterloo.ca) or the undergrad advising email [sasugradadv@uwaterloo.ca](mailto:sasugradadv@uwaterloo.ca).

# Lecture 1, January 08, 2024
In this lecture, we went over
1. Course syllabus and rules
2. Chapter 1 -- Basic definition of probability. We also saw the potential ambiguities when defining probabilities.


# Lecture 2, January 10, 2024

In this lecture, we went over some basic definitions from the set theory, and using them as the building block for the rest of the course. We started Chapter 2 today, with many definitions.

As for the set operations, $\cup,\cap,A^c,...$, the Venn diagrams help to visual the meaning behind. Here is a good reference [HERE](https://www.edrawmax.com/article/venn-diagram-symbols-and-set-notations.html).