<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Resampling, Jackknife and Bootstrap – STAT 8670 - Computational Methods in Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-smoothing.html" rel="next">
<link href="./05-cv.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c331ea236564e4415b565911d3f29016.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="custom-callouts.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STAT 8670 - Computational Methods in Statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/chikuang/Teaching-Stat8670"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="././STAT-8670---Computational-Methods-in-Statistics.pdf"> <i class="bi bi-file-pdf" role="img" aria-label="Download PDF">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-resample.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Resampling, Jackknife and Bootstrap</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Structure and R Programming</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Numerical Approaches and Optimization in 1-D</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-generating-rv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Generating Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-monte-carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Monte Carlo Simulation and Variance Reduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-cv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Cross Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-resample.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Resampling, Jackknife and Bootstrap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-smoothing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Smoothing Techniques in Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-density.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Density Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./other-topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Additional Topics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendix</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./App_A-intro-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Appendix: Introduction to R?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./App_B-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Appendix: Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./App_C_Rpackage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Appendix: Project &amp; R Package</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./APP_D_integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Appendix: Numerical integration</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">6.1</span> Introduction</a></li>
  <li><a href="#disclaimer" id="toc-disclaimer" class="nav-link" data-scroll-target="#disclaimer"><span class="header-section-number">6.2</span> Disclaimer</a></li>
  <li><a href="#resampling-methods" id="toc-resampling-methods" class="nav-link" data-scroll-target="#resampling-methods"><span class="header-section-number">6.3</span> Resampling methods</a></li>
  <li><a href="#estimators" id="toc-estimators" class="nav-link" data-scroll-target="#estimators"><span class="header-section-number">6.4</span> Estimators</a>
  <ul class="collapse">
  <li><a href="#bias-variance-tradeoff-of-an-estimator" id="toc-bias-variance-tradeoff-of-an-estimator" class="nav-link" data-scroll-target="#bias-variance-tradeoff-of-an-estimator"><span class="header-section-number">6.4.1</span> Bias-Variance Tradeoff of an estimator</a></li>
  </ul></li>
  <li><a href="#bootstrap" id="toc-bootstrap" class="nav-link" data-scroll-target="#bootstrap"><span class="header-section-number">6.5</span> Bootstrap</a>
  <ul class="collapse">
  <li><a href="#bootstrap-estimation-of-standard-error" id="toc-bootstrap-estimation-of-standard-error" class="nav-link" data-scroll-target="#bootstrap-estimation-of-standard-error"><span class="header-section-number">6.5.1</span> Bootstrap Estimation of Standard Error</a></li>
  <li><a href="#bootstrap-estimation-of-bias" id="toc-bootstrap-estimation-of-bias" class="nav-link" data-scroll-target="#bootstrap-estimation-of-bias"><span class="header-section-number">6.5.2</span> Bootstrap Estimation of Bias</a></li>
  </ul></li>
  <li><a href="#jackknife" id="toc-jackknife" class="nav-link" data-scroll-target="#jackknife"><span class="header-section-number">6.6</span> Jackknife</a>
  <ul class="collapse">
  <li><a href="#jackknife-estimate-of-bias" id="toc-jackknife-estimate-of-bias" class="nav-link" data-scroll-target="#jackknife-estimate-of-bias"><span class="header-section-number">6.6.1</span> Jackknife Estimate of Bias</a></li>
  <li><a href="#jackknife-estimate-of-standard-error" id="toc-jackknife-estimate-of-standard-error" class="nav-link" data-scroll-target="#jackknife-estimate-of-standard-error"><span class="header-section-number">6.6.2</span> Jackknife Estimate of Standard Error</a></li>
  <li><a href="#jackknife-does-not-always-work" id="toc-jackknife-does-not-always-work" class="nav-link" data-scroll-target="#jackknife-does-not-always-work"><span class="header-section-number">6.6.3</span> Jackknife does not always work</a></li>
  <li><a href="#other-variations-of-the-jackknife-estimations" id="toc-other-variations-of-the-jackknife-estimations" class="nav-link" data-scroll-target="#other-variations-of-the-jackknife-estimations"><span class="header-section-number">6.6.4</span> Other variations of the Jackknife estimations</a></li>
  </ul></li>
  <li><a href="#bootstrap-confidence-interval" id="toc-bootstrap-confidence-interval" class="nav-link" data-scroll-target="#bootstrap-confidence-interval"><span class="header-section-number">6.7</span> Bootstrap Confidence Interval</a>
  <ul class="collapse">
  <li><a href="#standard-normal-bootstrap-ci" id="toc-standard-normal-bootstrap-ci" class="nav-link" data-scroll-target="#standard-normal-bootstrap-ci"><span class="header-section-number">6.7.1</span> Standard Normal Bootstrap CI</a></li>
  <li><a href="#basic-bootstrap-ci" id="toc-basic-bootstrap-ci" class="nav-link" data-scroll-target="#basic-bootstrap-ci"><span class="header-section-number">6.7.2</span> Basic Bootstrap CI</a></li>
  <li><a href="#bootstrap-percentile-ci" id="toc-bootstrap-percentile-ci" class="nav-link" data-scroll-target="#bootstrap-percentile-ci"><span class="header-section-number">6.7.3</span> Bootstrap Percentile CI</a></li>
  <li><a href="#bootstrap-t-ci" id="toc-bootstrap-t-ci" class="nav-link" data-scroll-target="#bootstrap-t-ci"><span class="header-section-number">6.7.4</span> Bootstrap t CI</a></li>
  </ul></li>
  <li><a href="#others" id="toc-others" class="nav-link" data-scroll-target="#others"><span class="header-section-number">6.8</span> Others</a></li>
  <li><a href="#side-reading-wont-be-on-the-exam" id="toc-side-reading-wont-be-on-the-exam" class="nav-link" data-scroll-target="#side-reading-wont-be-on-the-exam"><span class="header-section-number">6.9</span> Side reading (Won’t be on the exam)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Resampling, Jackknife and Bootstrap</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">6.1</span> Introduction</h2>
<p>This chapter continues from the previous chapter, introducing more resampling methods; jackknife and bootstrap techniques.</p>
</section>
<section id="disclaimer" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="disclaimer"><span class="header-section-number">6.2</span> Disclaimer</h2>
<p>Most of the contents of this chapter are mainly from the reference book, Chapter 8 of Rizzo, M.L. (2007). <em>Statistical Computing with R</em>. CRC Press, Roca Baton.</p>
</section>
<section id="resampling-methods" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="resampling-methods"><span class="header-section-number">6.3</span> Resampling methods</h2>
<p><em>Resampling methods</em> is a way to use the observed data to generate hypothetical samples. It treats an observed sample as a <em>finite population</em>, and random samples are generated/resampled from it to estimate population characteristics and make inferences about the sampled population. It is useful when:</p>
<ul>
<li><p>Do not know the underlying distribution of a population</p></li>
<li><p>The formula may be difficult to be calculated.</p></li>
</ul>
<p>Some commonly used resampling methods include:</p>
<ul>
<li><p><strong>Cross-validation</strong>: Cross-validation is a model validation technique for assessing how the results of a statistical analysis will generalize to an independent data set. It is mainly used in settings where the goal is prediction, and one wants to estimate how accurately a predictive model will perform in practice.</p></li>
<li><p><strong>Bootstrap</strong>: Bootstrap methods are often used when the distribution of the target population is not specified; the sample is the only information available.</p></li>
<li><p><strong>Jackknife</strong>: The jackknife is a resampling technique used to estimate the bias and variance of a statistic. It is like a leave-one-out (LOO) cross-validation.</p></li>
<li><p><strong>Permutation tests</strong>: Permutation tests are a type of non-parametric statistical test that involves rearranging the data points to test a hypothesis. They are used to determine whether the observed effect is statistically significant by comparing it to the distribution of effects obtained through random permutations of the data.</p></li>
</ul>
</section>
<section id="estimators" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="estimators"><span class="header-section-number">6.4</span> Estimators</h2>
<section id="bias-variance-tradeoff-of-an-estimator" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="bias-variance-tradeoff-of-an-estimator"><span class="header-section-number">6.4.1</span> Bias-Variance Tradeoff of an estimator</h3>
<p>In statistics, the bias-variance tradeoff is the property of a model that the variance of the parameter estimated across samples can be reduced by increasing the bias in the estimated parameters. If we look at the Mean square error (MSE) of an estimator <span class="math inline">\(\hat \theta\)</span> for a parameter <span class="math inline">\(\theta\)</span>:</p>
<div class="callout-definition" title="Mean Square Errors">
<p>Suppose we have a parameter <span class="math inline">\(\theta\)</span> and an estimator <span class="math inline">\(\hat \theta\)</span>. The mean square error (MSE) of the estimator is defined as <span class="math display">\[\mathrm{MSE}_{\theta}(\hat \theta)=\mathbb E[(\hat \theta-\theta )^2 ]= \mathbb{V}ar(\hat \theta) + [\mathbb b(\hat \theta)]^2,\]</span> where <span class="math inline">\(\mathbb b\)</span> is the bias of the estimator.</p>
</div>
<div id="callout-1" class="callout callout-style-default callout-note callout-titled" title="Derivation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Derivation
</div>
</div>
<div class="callout-body-container callout-body">
<p>We start with the definition of the mean squared error (MSE):</p>
<p><span class="math display">\[
\mathrm{MSE}_\theta(\hat \theta)
= \mathbb E\big[(\hat \theta- \theta)^2\big].
\]</span></p>
<p>Add and subtract <span class="math inline">\(\mathbb E[\hat \theta]\)</span> inside the square: <span class="math display">\[
\mathbb E\big[(\hat \theta- \theta)^2\big]
= \mathbb E\big[(\hat \theta- \mathbb E[\hat \theta] + \mathbb E[\hat \theta] - \theta)^2\big].
\]</span></p>
<p>Expand the square: <span class="math display">\[
\mathbb E\big[(\hat \theta- \mathbb E[\hat \theta])^2\big]
+ 2\,\mathbb E\big[(\hat \theta- \mathbb E[\hat \theta])(\mathbb E[\hat \theta] - \theta)\big]
+ (\mathbb E[\hat \theta] - \theta)^2.
\]</span></p>
<p>The middle term vanishes because <span class="math display">\[
\mathbb E\big[\hat \theta- \mathbb E[\hat \theta]\big] = 0.
\]</span></p>
<p>Hence, <span class="math display">\[
\mathbb E\big[(\hat \theta- \theta)^2\big]
= \mathbb E\big[(\hat \theta- \mathbb E[\hat \theta])^2\big]
+ (\mathbb E[\hat \theta] - \theta)^2.
\]</span></p>
<p>Recognizing that <span class="math display">\[
\mathbb{V}ar(\hat \theta) = \mathbb E\big[(\hat \theta- \mathbb E[\hat \theta])^2\big]
\quad \text{and} \quad
b(\hat \theta) = \mathbb E[\hat \theta] - \theta,
\]</span> we obtain the bias–variance decomposition: <span class="math display">\[
\boxed{
\mathbb E\big[(\hat \theta- \theta)^2\big]
= \mathbb{V}ar(\hat \theta) + \mathbb b^2(\hat \theta)^2.}
\]</span></p>
</div>
</div>
<p><strong>Questions</strong>: Why do we care about the bias? Can we always find an unbiased estimator? What does it mean?</p>
<p>For most of the course, we focus on the <em>unbiased estimator</em>. This may often be obtained from using the LLN. Then, such as in the MC Chapter, we can compare the (relative) efficiency between the estimators, and discuss about the variance reduction.</p>
</section>
</section>
<section id="bootstrap" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="bootstrap"><span class="header-section-number">6.5</span> Bootstrap</h2>
<p>Bootstrap estimates of a sampling distribution are analogous to the idea of <em>density estimation</em> (will be introduced in a later chapter). We construct a histogram of a sample to obtain an estimate of the shape of the density function. The histogram is not the density, but in a nonparametric problem, can be viewed as a reasonable estimate of the density. We have methods to generate random samples from completely specified densities; bootstrap generates random samples from the empirical distribution of the sample.</p>
<p>Suppose we have an observed random sample <span class="math inline">\(x=(x_1,\dots,x_n)\)</span> from a distribution <span class="math inline">\(F\)</span>. If <span class="math inline">\(X^\ast\)</span> is selected at random from <span class="math inline">\(x\)</span>, then <span class="math display">\[P(X^\ast=x_i)=1/n,\quad i=1,\dots,n.\]</span></p>
<p>Resampling generates a random sample <span class="math inline">\(X^\ast_1,\dots,X_n^\ast\)</span> by <em>sampling with replacement</em> from the observed sample <span class="math inline">\(x\)</span>. Then the RVs <span class="math inline">\(X_i^\ast\)</span> are i.i.d. and uniformly distributed on the observed data points <span class="math inline">\(\{x_1,\dots,x_n\}\)</span>.</p>
<p>The empirical distribution function (ecdf) <span class="math inline">\(F_n(x)\)</span> is an estimator of <span class="math inline">\(F(x)\)</span>. It can be shown that <span class="math inline">\(F_n(x)\)</span> is a sufficient statistic for <span class="math inline">\(F(x)\)</span>; that is, all the information about <span class="math inline">\(F(x)\)</span> that is contained in the sample is also contained in <span class="math inline">\(F_n(x)\)</span>. Moreover, <span class="math inline">\(F_n(x)\)</span> is itself the distribution function of a random variable; namely the random variable that is uniformly distributed on the set <span class="math inline">\(\{x_1, \dots , x_n\}\)</span>. Hence the empirical cdf <span class="math inline">\(F_n\)</span> is the cdf of <span class="math inline">\(X^\ast\)</span>. Thus in bootstrap, there are two approximations. The ecdf <span class="math inline">\(F_n\)</span> is an approximation to the cdf <span class="math inline">\(F_X\)</span>. The ecdf <span class="math inline">\(F_m^\ast\)</span> of the bootstrap replicates is an approximation to the ecdf <span class="math inline">\(F_n\)</span>. Resampling from the sample <span class="math inline">\(x\)</span> is equivalent to generating random samples from the distribution <span class="math inline">\(F_n(x)\)</span>. The two approximations can be represented by the diagram</p>
<p><span class="math display">\[
\begin{aligned}
F &amp; \rightarrow X \rightarrow F_n \\
F_n &amp; \rightarrow X^* \rightarrow F_n^* .
\end{aligned}
\]</span></p>
<p>To generate a bootstrap random sample by resampling <span class="math inline">\(x\)</span>, generate <span class="math inline">\(n\)</span> random integers <span class="math inline">\(\{i_1,\dots, i_n\}\)</span> uniformly distributed on <span class="math inline">\(\{1,\dots , n\}\)</span> and select the bootstrap sample <span class="math inline">\(x^\ast = (x_{i_1} ,\dots , x_{i_n} )\)</span>.</p>
<hr>
<p>Let <span class="math inline">\(\theta\)</span> be the parameter of interest (could be a vector), and <span class="math inline">\(\hat \theta\)</span> be its estimator. Then the bootstrap estimate of the distribution of <span class="math inline">\(\hat \theta\)</span> is obtained as follows.</p>
<div class="callout-algorithm" title="Procedure of Bootstrap">
<ol type="1">
<li>For each bootstrap replicate, indexed <span class="math inline">\(b = 1, \dots, B\)</span>:
<ol type="a">
<li>Generate sample <span class="math inline">\(x^{\ast (b)} = x_1^\ast,\dots,x_n^\ast\)</span> by sampling with replacement from the observed sample <span class="math inline">\(x_1,\dots,x_n\)</span>.</li>
<li>Compute the <span class="math inline">\(b\)</span>th replicate <span class="math inline">\(\hat \theta^{(b)}\)</span> from the <span class="math inline">\(b\)</span>th bootstrap sample.</li>
</ol></li>
<li>The bootstrap estimate of <span class="math inline">\(F_{\hat \theta}(\cdot)\)</span> is the empirical distribution of the replicates <span class="math inline">\(\hat \theta^{(1)},\dots ,\hat \theta^{(B)}\)</span>.</li>
</ol>
</div>
<div class="callout-example" title="Empirical CDF and Bootstrap Distribution">
<p>Suppose that we have observed the sample</p>
<p><span class="math display">\[x = \{2, 2, 1, 1, 5, 4, 4, 3, 1, 2\}.\]</span></p>
<p>Resampling from <span class="math inline">\(x\)</span> we select <span class="math inline">\(1, 2, 3, 4\)</span>, or <span class="math inline">\(5\)</span> with probabilities <span class="math inline">\(0.3, 0.3, 0.1, 0.2\)</span>, and <span class="math inline">\(0.1\)</span>, respectively, so the cdf <span class="math inline">\(F_{X^\ast}\)</span> of a randomly selected replicate is exactly the ecdf <span class="math inline">\(F_n(x)\)</span>:</p>
<p><span class="math display">\[
F_{X *}(x)=F_n(x)= \begin{cases}0, &amp; x&lt;1 ; \\ 0.3, &amp; 1 \leq x&lt;2 ; \\ 0.6, &amp; 2 \leq x&lt;3 ; \\ 0.7, &amp; 3 \leq x&lt;4 ; \\ 0.9, &amp; 4 \leq x&lt;5 ; \\ 1, &amp; x \geq 5 .\end{cases}
\]</span></p>
<p>Note that if <span class="math inline">\(F_n\)</span> is not close to <span class="math inline">\(F_X\)</span> then the distribution of the replicates will not be close to <span class="math inline">\(F_X\)</span>. The sample <span class="math inline">\(x\)</span> above is actually a sample from a Poisson(2) distribution. Resampling from <span class="math inline">\(x\)</span> a large number of replicates produces a good estimate of <span class="math inline">\(F_n\)</span> but not a good estimate of <span class="math inline">\(F_X\)</span> , because regardless of how many replicates are drawn, the bootstrap samples will never include <span class="math inline">\(0\)</span>.</p>
</div>
<section id="bootstrap-estimation-of-standard-error" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="bootstrap-estimation-of-standard-error"><span class="header-section-number">6.5.1</span> Bootstrap Estimation of Standard Error</h3>
<p>Recall that, in normal approximate, the <span class="math inline">\(100(1-\alpha)\)</span>% confidence interval (for <span class="math inline">\(\mu\)</span>) is given as <span class="math display">\[
  \bar{x}_n \pm z_{1-\alpha/2} \frac{\sigma}{\sqrt{n}}.
\]</span> In the above formula, we refer</p>
<ul>
<li><span class="math inline">\(\sigma/\sqrt{n}\)</span>: as the <strong>standard error</strong> (se).</li>
<li><span class="math inline">\(z_{1-\alpha/2}\cdot \sigma/\sqrt{n}\)</span>: as the <strong>margin of error</strong>.</li>
</ul>
<div class="callout-definition" title="Standard Error">
<p>The standard error (SE) of a statistic is the standard deviation of its sampling distribution. The se is often used in calculations of confidence intervals.</p>
</div>
<p>To estimate the <span class="math inline">\(se\)</span> of an estimator <span class="math inline">\(\hat \theta\)</span>, we can use the bootstrap method. Let <span class="math inline">\(\hat \theta^{(1)},\dots,\hat \theta^{(B)}\)</span> be the bootstrap replicates. The bootstrap estimate of the standard error of <span class="math inline">\(\hat \theta\)</span> is given by the sample standard deviation of the replicates:</p>
<p><span class="math display">\[
\widehat{s e}\left(\hat{\theta}^*\right)=\sqrt{\frac{1}{B-1} \sum_{b=1}^B\left(\hat{\theta}^{(b)}-\overline{\hat{\theta}^*}\right)^2},
\]</span> where <span class="math inline">\(\overline{\hat{\theta}^*}=\frac{1}{B} \sum_{b=1}^B \hat{\theta}^{(b)}\)</span>.</p>
<div id="callout-2" class="callout callout-style-default callout-note callout-titled" title="Remark for estimating se">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark for estimating se
</div>
</div>
<div class="callout-body-container callout-body">
<p>The number of replicates needed for good estimates of standard error is not large; <span class="math inline">\(B = 50\)</span> is usually large enough, and rarely is <span class="math inline">\(B &gt; 200\)</span> necessary.</p>
</div>
</div>
<div class="callout-example" title="Bootstrap Estimate of Standard Error">
<p>The law school data set law in the <em>bootstrap</em> package. The data frame contains LSAT (average score on law school admission test score) and GPA (average undergraduate grade point average) for 15 law schools.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Observation</th>
<th>LSAT</th>
<th>GPA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>576</td>
<td>339</td>
</tr>
<tr class="even">
<td>2</td>
<td>635</td>
<td>330</td>
</tr>
<tr class="odd">
<td>3</td>
<td>558</td>
<td>281</td>
</tr>
<tr class="even">
<td>4</td>
<td>578</td>
<td>303</td>
</tr>
<tr class="odd">
<td>5</td>
<td>666</td>
<td>344</td>
</tr>
<tr class="even">
<td>6</td>
<td>580</td>
<td>307</td>
</tr>
<tr class="odd">
<td>7</td>
<td>555</td>
<td>300</td>
</tr>
<tr class="even">
<td>8</td>
<td>661</td>
<td>343</td>
</tr>
<tr class="odd">
<td>9</td>
<td>651</td>
<td>336</td>
</tr>
<tr class="even">
<td>10</td>
<td>605</td>
<td>313</td>
</tr>
<tr class="odd">
<td>11</td>
<td>653</td>
<td>312</td>
</tr>
<tr class="even">
<td>12</td>
<td>575</td>
<td>274</td>
</tr>
<tr class="odd">
<td>13</td>
<td>545</td>
<td>276</td>
</tr>
<tr class="even">
<td>14</td>
<td>572</td>
<td>288</td>
</tr>
<tr class="odd">
<td>15</td>
<td>594</td>
<td>296</td>
</tr>
</tbody>
</table>
<p>This data set is a random sample from the universe of 82 law schools in law82 (bootstrap). Estimate the correlation between LSAT and GPA scores, and compute the bootstrap estimate of the standard error of the sample correlation.</p>
<p>The bootstrap procedure is</p>
<ol type="1">
<li>For each bootstrap replicate, indexed <span class="math inline">\(b = 1,\dots , B\)</span>
<ol type="a">
<li>Generate sample <span class="math inline">\((\text{LSAT}^{\ast (b)}_i, \text{GPA}^{\ast (b)}_i), i = 1,\dots , n\)</span> by sampling with replacement from the observed sample.</li>
<li>Compute the <span class="math inline">\(b\)</span>th replicate of the correlation <span class="math inline">\(\hat \theta^{(b)} = \mathbb{C}orr(\text{LSAT}^{\ast (b)}, \text{GPA}^{\ast (b)})\)</span> from the <span class="math inline">\(b\)</span>th bootstrap sample.</li>
</ol></li>
<li>The bootstrap estimate of the standard error of <span class="math inline">\(\hat \theta\)</span> is the sample standard deviation of the replicates <span class="math inline">\(\hat \theta^{(1)},\dots ,\hat \theta^{(B)}\)</span>, <span class="math inline">\(\{R^{(i)}\}_{i=1}^B\)</span></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bootstrap) <span class="co">#for the law data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">cor</span>(law<span class="sc">$</span>LSAT, law<span class="sc">$</span>GPA)) <span class="co"># 15 sampled schools in hand</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7763745</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">cor</span>(law82<span class="sc">$</span>LSAT, law82<span class="sc">$</span>GPA)) <span class="co"># all total 82 schools</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7599979</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#set up the bootstrap</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">200</span> <span class="co">#number of replicates</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(law) <span class="co">#sample size</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="fu">numeric</span>(B) <span class="co">#storage for replicates</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#bootstrap estimate of standard error of R</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (b <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># randomly select the indices</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  LSAT <span class="ot">&lt;-</span> law<span class="sc">$</span>LSAT[i] <span class="co"># i is a vector of indices</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  GPA <span class="ot">&lt;-</span> law<span class="sc">$</span>GPA[i]</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  R[b] <span class="ot">&lt;-</span> <span class="fu">cor</span>(LSAT, GPA)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">#output</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>(se.R <span class="ot">&lt;-</span> <span class="fu">sd</span>(R))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.128997</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(R, <span class="at">prob =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-resample_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bootstrap estimate of se(R) is 0.129. The normal theory estimate for standard error of R is 0.115.</p>
</div>
<div class="callout-example" title="Bootstrap Estimate of Standard Error using *boot* function">
<p>We can also use the <code>boot(.)</code> function in the <code>boot</code> package to compute the bootstrap estimate of standard error.</p>
<p>First, write a function that returns <span class="math inline">\(\hat \theta(b)\)</span>, where the first argument to the function is the sample data, and the second argument is the vector <span class="math inline">\(\{i_1, \dots , i_n\}\)</span> of indices. If the data is <span class="math inline">\(x\)</span> and the vector of indices is i, we need <span class="math inline">\(x[i,1]\)</span> to extract the first resampled variable, and x[i,2] to extract the second resampled variable. The code and output is shown below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>my_r <span class="ot">&lt;-</span> <span class="cf">function</span>(x, i) {</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># want correlation of columns 1 and 2</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(x[i, <span class="dv">1</span>], x[i, <span class="dv">2</span>])</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The printed summary of output from the boot function is obtained by the command boot or the result can be saved in an object for further analysis. Here we save the result in obj and print the summary.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot) <span class="co">#for boot function</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">777</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>(obj <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> bootstrap<span class="sc">::</span>law, <span class="at">statistic =</span> my_r, <span class="at">R =</span> <span class="dv">2000</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = bootstrap::law, statistic = my_r, R = 2000)


Bootstrap Statistics :
     original      bias    std. error
t1* 0.7763745 -0.01075929   0.1364617</code></pre>
</div>
</div>
<p>The observed value <span class="math inline">\(\hat \theta\)</span> of the correlation statistic is labeled t1*. The bootstrap estimate of standard error of the estimate is <span class="math inline">\(se(\hat \theta) =\)</span> 0.1365, based on 2000 replicates. Note that the standard deviation of the replicates can be computed directly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(obj<span class="sc">$</span>t)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1364617</code></pre>
</div>
</div>
</div>
</section>
<section id="bootstrap-estimation-of-bias" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="bootstrap-estimation-of-bias"><span class="header-section-number">6.5.2</span> Bootstrap Estimation of Bias</h3>
<p>Recall that a bias of an estimator <span class="math inline">\(\hat \theta\)</span> is defined as <span class="math display">\[
\mathbb b(\hat \theta) = \mathbb E[\hat \theta] - \theta.
\]</span></p>
<p>An example of a biased estimator is the MLE of variance, <span class="math inline">\(\hat{\sigma}^2 = \sum (X_i-\bar{X}_n)^2/n\)</span> of <span class="math inline">\(\sigma^2 = \sum (X_i-\bar{X}_n)^2/(n-1)\)</span>, which has expected value <span class="math inline">\((1 − 1/n)\sigma^2\)</span>. Here, the bias is <span class="math inline">\(−\sigma^2/n\)</span>.</p>
<p>The bootstrap estimation of bias uses the bootstrap replicates of <span class="math inline">\(\hat \theta\)</span> to estimate the sampling distribution of <span class="math inline">\(\hat \theta\)</span>. For the finite population <span class="math inline">\(x = (x_1,\dots , x_n)\)</span>, the parameter is <span class="math inline">\(\hat \theta(x)\)</span> and there are <span class="math inline">\(B\)</span> i.i.d. estimators <span class="math inline">\(\hat \theta^{(b)}\)</span>. The sample mean of the replicates <span class="math inline">\(\{\hat \theta(b)\}\)</span> is unbiased for its expected value <span class="math inline">\(\mathbb E[\hat \theta^\ast]\)</span>, so the bootstrap estimate of bias is<br>
<span class="math display">\[\mathbb b(\hat \theta) = \hat \theta^\ast − \hat \theta,\]</span> where <span class="math inline">\(\hat \theta^\ast  = \sum_{b=1}^B \hat \theta^{(b)}\)</span>, and <span class="math inline">\(\hat \theta= \hat \theta(x)\)</span> is the estimate computed from the original observed sample. (In bootstrap <span class="math inline">\(F_n\)</span> is sampled in place of <span class="math inline">\(F_X\)</span> , so we replace <span class="math inline">\(\theta\)</span> with <span class="math inline">\(\hat \theta\)</span> to estimate the bias.)</p>
<div id="callout-3" class="callout callout-style-default callout-note callout-titled" title="Remark for estimating bias">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark for estimating bias
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><span class="math inline">\(\oplus\)</span> Positive bias indicates that <span class="math inline">\(\hat \theta\)</span> on average tends to overestimate <span class="math inline">\(\theta\)</span>,</p></li>
<li><p><span class="math inline">\(\ominus\)</span> Negative bias is on average underestimate <span class="math inline">\(\theta\)</span></p></li>
</ul>
</div>
</div>
<div class="callout-example" title="Bootstrap Estimate of Bias">
<p>In the law data example, compute the bootstrap estimate of bias in the sample correlation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sample estimate for n=15</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>theta.hat <span class="ot">&lt;-</span> <span class="fu">cor</span>(law<span class="sc">$</span>LSAT, law<span class="sc">$</span>GPA)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap estimate of bias</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">2000</span> <span class="co"># larger for estimating bias</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(law)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>theta.b <span class="ot">&lt;-</span> <span class="fu">numeric</span>(B)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (b <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  LSAT <span class="ot">&lt;-</span> law<span class="sc">$</span>LSAT[i]</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  GPA <span class="ot">&lt;-</span> law<span class="sc">$</span>GPA[i]</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  theta.b[b] <span class="ot">&lt;-</span> <span class="fu">cor</span>(LSAT, GPA)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>(bias <span class="ot">&lt;-</span> <span class="fu">mean</span>(theta.b <span class="sc">-</span> theta.hat))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.001063244</code></pre>
</div>
</div>
<p>The estimate of bias is -0.0011. Note that this is close to the estimate of bias returned by the boot function we used before.</p>
</div>
<div class="callout-example" title="One more example of Bootstrap estimation of bias">
<p>The <code>patch</code> data from the <em>bootstrap</em> package contains measurements of a certain hormone in the bloodstream of 8 subjects after wearing a medical patch. The parameter of interest is</p>
<p><span class="math display">\[
\theta\coloneqq\frac{\mathbb E(\text { new })-\mathbb E(\text { old })}{\mathbb E(\text { old })-\mathbb E(\text { placebo })}
\]</span></p>
<p>If <span class="math inline">\(|\theta| \ge 0.20\)</span>, this indicates bioequivalence of the old and new patches. The statistic is <span class="math inline">\(\bar{Y} /\bar{Z}\)</span>. Compute a bootstrap estimate of bias in the bioequivalence ratio statistic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(patch, <span class="at">package =</span> <span class="st">"bootstrap"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(patch)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  subject placebo oldpatch newpatch    z     y
1       1    9243    17649    16449 8406 -1200
2       2    9671    12013    14614 2342  2601
3       3   11792    19979    17274 8187 -2705
4       4   13357    21816    23798 8459  1982
5       5    9055    13850    12560 4795 -1290
6       6    6290     9806    10157 3516   351</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(patch) <span class="co">#in bootstrap package</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>theta.b <span class="ot">&lt;-</span> <span class="fu">numeric</span>(B)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>theta.hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(patch<span class="sc">$</span>y) <span class="sc">/</span> <span class="fu">mean</span>(patch<span class="sc">$</span>z)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (b <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> patch<span class="sc">$</span>y[i]</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> patch<span class="sc">$</span>z[i]</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  theta.b[b] <span class="ot">&lt;-</span> <span class="fu">mean</span>(y) <span class="sc">/</span> <span class="fu">mean</span>(z)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>bias <span class="ot">&lt;-</span> <span class="fu">mean</span>(theta.b) <span class="sc">-</span> theta.hat</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sd</span>(theta.b)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">Estimate =</span> theta.hat,</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">Bias =</span> bias,</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE =</span> se,</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">CV =</span> bias <span class="sc">/</span> se</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(result, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">caption =</span> <span class="st">"Bootstrap results for correlation estimate"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Bootstrap results for correlation estimate</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Bias</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">CV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-0.071</td>
<td style="text-align: right;">0.006</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">0.061</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If <span class="math inline">\(|\mathbb b|/se \le 0.25\)</span>, it is not usually necessary to adjust for bias. The <span class="math inline">\(\mathbb b\)</span> is small relative to standard error ( <span class="math inline">\(\mathbb b/se &lt; 0.08\)</span>), so in this example it is not necessary to adjust for bias.</p>
</div>
</section>
</section>
<section id="jackknife" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="jackknife"><span class="header-section-number">6.6</span> Jackknife</h2>
<p>The jackknife is another resampling technique used to estimate the bias and variance of a statistic.</p>
<p>Jackknife is similar to <strong>leave-one-out cross-validation</strong> (LOOCV). Let <span class="math inline">\(\mathbf{x}= (x_1,\dots,x_n)\)</span> be an observed random sample, and denote the <span class="math inline">\(i\)</span>th jackknife sample by <span class="math inline">\(\mathbf{x}_{-i} = (x_1,\dots,x_{i-1},x_{i+1},\dots,x_n)\)</span>, that is, a subset of <span class="math inline">\(\mathbf{x}\)</span>.</p>
<p>Jackknife can be used to:</p>
<ul>
<li>Estimating bias,</li>
<li>Estimating standard error</li>
<li>Detecting influential observations</li>
<li>Many others</li>
</ul>
<p>For the parameter of interest <span class="math inline">\(\theta\)</span>, if the statistics is <span class="math inline">\(T(\mathbf{x})=: \hat \theta\)</span> is computed on the full</p>
<p>Jackknife is a special kind of <em>Cross-validation</em> where we <em>leave-one-out</em> (LOO) the observation, and calculate the quantities on the remaining data. To fix the idea, let <span class="math inline">\(x=(x_1,\dots,x_n)\)</span> be the observed data of samele size <span class="math inline">\(n\)</span>. The <span class="math inline">\(i\)</span>th jackknife sample is defined as <span class="math inline">\(x_{(i)}=(x_1,\dots,x_{i-1},x_{i+1},\dots,x_n)\)</span>, that is, the sample with the <span class="math inline">\(i\)</span>th observation removed. Let <span class="math inline">\(\hat \theta=T_n(x)\)</span> be the estimator of the parameter of interest <span class="math inline">\(\theta\)</span>. The <span class="math inline">\(i\)</span>th jackknife replicate is defined as <span class="math inline">\(\hat \theta_{(i)}=T(x_{(i)})\)</span>, that is, the estimate computed from the <span class="math inline">\(i\)</span>th jackknife sample. The jackknife estimate of bias is defined as</p>
<section id="jackknife-estimate-of-bias" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="jackknife-estimate-of-bias"><span class="header-section-number">6.6.1</span> Jackknife Estimate of Bias</h3>
<p>If <span class="math inline">\(\hat \theta\)</span> is a smooth statistic, then <span class="math inline">\(\hat \theta_{(\cdot)} = t(F_{n−1}(x_{(i)}))\)</span>, and the jackknife estimate of bias is <span class="math display">\[
\hat{\mathbb b}_{jack} = (n − 1)(\overline{\hat \theta_{(\cdot)}} − \hat \theta),
\]</span> where <span class="math inline">\(\overline{\hat \theta_{(\cdot)}}=\frac{1}{n} \sum_{i=1}^n \hat \theta_{(i)}\)</span> is the average of the estimate from LOO samples, and <span class="math inline">\(\hat \theta=\hat \theta(x)\)</span> is the estimate from the original observed sample.</p>
<div id="callout-4" class="callout callout-style-default callout-note callout-titled" title="Question: Where is $n-1$ coming from?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Question: Where is <span class="math inline">\(n-1\)</span> coming from?
</div>
</div>
<div class="callout-body-container callout-body">
<p>For instance, in the case of <span class="math inline">\(\theta\)</span> is the population variance <span class="math inline">\(\theta=\sigma^2\)</span>. Let <span class="math inline">\(x_1,\dots,x_n\)</span> be random samples from <span class="math inline">\(F_X\)</span>, the variance is <span class="math display">\[
\mathbb E[(X - \mu)^2] =: \theta,
\]</span> and the plug-in estimator is <span class="math display">\[
\hat \theta= \frac{1}{n} \sum_{i=1}^n (x_i - \bar x_n)^2.
\]</span> This estimator <span class="math inline">\(\hat \theta\)</span> is biased, and the bias is <span class="math display">\[
\mathbb b(\hat \theta)=\mathbb E\left[\hat \theta-\theta\right]=\frac{n-1}{n} \sigma^2-\sigma^2=-\frac{\sigma^2}{n}.
\]</span> Since Jackknife is a resampling method, we compute the jackknife replicates <span class="math inline">\(\hat \theta_{(i)}\)</span> by leaving one observation out for each of the <span class="math inline">\(i\)</span> on sample size <span class="math inline">\(n-1\)</span>, so the bias in the jackknife replicates is <span class="math inline">\(-\sigma^2/(n-1)\)</span>. Thus, for each <span class="math inline">\(i,~i=1,\dots,n\)</span>, we have <span class="math display">\[
\begin{aligned}
\mathbb E\left[\hat \theta_{(i)}-\hat \theta\right] &amp; =\mathbb E\left[\hat \theta_{(i)}-\theta\right]-\mathbb E[\hat \theta-\theta] \\
&amp; =\mathbb b\left(\hat \theta_{(i)}\right)-\mathbb b(\hat \theta) \\
&amp; =-\frac{\sigma^2}{n-1}-\left(-\frac{\sigma^2}{n}\right) =-\frac{\sigma^2}{n(n-1)}=\frac{\mathbb b(\hat \theta)}{n-1} .
\end{aligned}
\]</span> Therefore, the <span class="math inline">\(n-1\)</span> factor appears in the jackknife estimate of bias formula results the unbiased estimate of the bias.</p>
</div>
</div>
<div id="callout-5" class="callout callout-style-default callout-note callout-titled" title="Leave one out (LOO) in R">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Leave one out (LOO) in R
</div>
</div>
<div class="callout-body-container callout-body">
<p>In R, we can use the <code>x[-i]</code> to perform LOO operation in a vector <span class="math inline">\(x=(x_1,\dots,x_n)\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>x[<span class="sc">-</span><span class="dv">3</span>] <span class="co"># leave the 3rd element out</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  4  8 10</code></pre>
</div>
</div>
</div>
</div>
<div class="callout-example" title="Jackknife Estimate of Bias">
<p>Compute the jackknife estimate of bias for the patch data in the <code>bootstrap</code> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(patch, <span class="at">package =</span> <span class="st">"bootstrap"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(patch)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> patch<span class="sc">$</span>y</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> patch<span class="sc">$</span>z</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>theta.hat <span class="ot">&lt;-</span> <span class="fu">mean</span>(y) <span class="sc">/</span> <span class="fu">mean</span>(z)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> (theta.hat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.0713061</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#compute the jackknife replicates, LOO estimates</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>theta.jack <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  theta.jack[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(y[<span class="sc">-</span>i]) <span class="sc">/</span> <span class="fu">mean</span>(z[<span class="sc">-</span>i])</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>(bias <span class="ot">&lt;-</span> (n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> (<span class="fu">mean</span>(theta.jack) <span class="sc">-</span> theta.hat) )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.008002488</code></pre>
</div>
</div>
</div>
</section>
<section id="jackknife-estimate-of-standard-error" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="jackknife-estimate-of-standard-error"><span class="header-section-number">6.6.2</span> Jackknife Estimate of Standard Error</h3>
<p>The jackknife estimate of standard error (se) is given by <span class="math display">\[
\boxed{\widehat{s e}_{j a c k}=\sqrt{\frac{n-1}{n} \sum_{i=1}^n\left(\hat{\theta}_{(i)}-\overline{\hat{\theta}_{(\cdot)}}\right)^2}},
\]</span> for smooth statistics <span class="math inline">\(\hat \theta\)</span>.</p>
<div id="callout-6" class="callout callout-style-default callout-note callout-titled" title="Where is the $(n-1)/n$ coming from?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Where is the <span class="math inline">\((n-1)/n\)</span> coming from?
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can first see an example in the context of the population mean. Suppose our parameter of interest is <span class="math inline">\(\theta=\mu\)</span> and <span class="math inline">\(\hat \theta=\bar{x}_n\)</span> is its estimator. Then the variance estimator of the <span class="math inline">\(\hat \theta\)</span> is <span class="math inline">\(\sqrt{\mathbb{V}ar(X)/n}\)</span>. Hence, the factor <span class="math inline">\((n-1)/n\)</span> makes <span class="math inline">\(\widehat{s e}_{j a c k}\)</span> an unbiased eestimator of the se of the mean.</p>
<p>The other way to look at this is that, we can consider a <em>plug-in estimate</em> of the se of the mean. For a continuous rv <span class="math inline">\(X~F_X\)</span>, suppose we have the random samples from <span class="math inline">\(F_X\)</span> and obtain <span class="math inline">\(\mathbf{x}=(x_1,\dots,x_n)\)</span>. The plug-in estimate of the variance of a them is the variance of <span class="math inline">\(Y\)</span> , where <span class="math inline">\(Y\)</span> is uniformly distributed on the sample <span class="math inline">\(x_1,\dots,x_n\)</span>. That is,</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\mathbb{V}ar}(Y) &amp; =\frac{1}{n} \mathbb E[Y-\mathbb E[Y]]^2=\frac{1}{n} \mathbb E[Y-\bar{X}]^2 \\
&amp; =\frac{1}{n} \sum_{i=1}^n\left(X_i-\bar{X}\right)^2 \cdot \frac{1}{n} \\
&amp; =\frac{n-1}{n^2} S_X^2=\frac{n-1}{n}[\widehat{\operatorname{se}}(\bar{X})]^2 .
\end{aligned}
\]</span></p>
<p>Thus, for the jackknife estimator of standard error, a factor of <span class="math inline">\(\{(n − 1)/n\}/2\)</span> gives the plug-in estimate of variance. The factors <span class="math inline">\(\{(n−1)/n\}/2\)</span> and <span class="math inline">\((n−1)/n\)</span> are approximately equal if <span class="math inline">\(n\)</span> is large. Researchers commented that the choice of the factor <span class="math inline">\((n − 1)/n\)</span> instead of <span class="math inline">\(\{(n − 1)/n\}/2\)</span> is somewhat arbitrary.</p>
</div>
</div>
<div class="callout-example" title="Jackknife Estimate of Standard Error">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>(se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((n<span class="dv">-1</span>) <span class="sc">*</span> <span class="fu">mean</span>((theta.jack <span class="sc">-</span> <span class="fu">mean</span>(theta.jack))<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1055</code></pre>
</div>
</div>
<p>The jackknife estimate of standard error is 0.1055 From the previous result for the bias, we have the estimated coefficient of variation</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> bias<span class="sc">/</span>se</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>tbl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">bias =</span> bias,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">se   =</span> se,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">cv   =</span> cv</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create kable table</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tbl, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">caption =</span> <span class="st">"Bias, Standard Error, and Coefficient of Variation"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">"center"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Bias, Standard Error, and Coefficient of Variation</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">bias</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">se</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">cv</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.008</td>
<td style="text-align: right;">0.106</td>
<td style="text-align: right;">0.076</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="jackknife-does-not-always-work" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="jackknife-does-not-always-work"><span class="header-section-number">6.6.3</span> Jackknife does not always work</h3>
<div id="callout-7" class="callout callout-style-default callout-note callout-titled" title="Jackknife does not always work">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Jackknife does not always work
</div>
</div>
<div class="callout-body-container callout-body">
<p>Q: When does jackknife not work?</p>
<p>Jackknife does not work when the function <span class="math inline">\(T(\cdot)\)</span> is <strong>not a smooth</strong> functional! Smoothness means that small changes in the data correspond to small changes in the statistic. For instance, median is a statisitics that is NOT smooth.</p>
</div>
</div>
<div class="callout-example" title="Jackknife fails for Median">
<p>Example 8.8 (Failure of jackknife). In this example the jackknife estimate of standard error of the median is computed for a random sample of 10 integers from <span class="math inline">\(1,\dots, 100\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">777</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, <span class="at">size =</span> n)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># jackknife estimate of se</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) { <span class="co"># leave one out</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> x[<span class="sc">-</span>i]</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  M[i] <span class="ot">&lt;-</span> <span class="fu">median</span>(y)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>Mbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(M)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap estimate of se</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>Mb <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="at">expr =</span> {</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">sample</span>(x, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">median</span>(y)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>est_jk <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> n <span class="sc">*</span> <span class="fu">sum</span>((M <span class="sc">-</span> Mbar)<span class="sc">^</span><span class="dv">2</span>)) <span class="co"># jackknife estimate</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>est_bs <span class="ot">&lt;-</span> <span class="fu">sd</span>(Mb) <span class="co"># bootstrap estimate</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>tbl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">Method =</span> <span class="fu">c</span>(<span class="st">"Jackknife"</span>, <span class="st">"Bootstrap"</span>),</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">Estimate =</span> <span class="fu">c</span>(est_jk, est_bs)</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Display table</span></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tbl, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">caption =</span> <span class="st">"Comparison of Jackknife and Bootstrap Estimates"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">"center"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>Comparison of Jackknife and Bootstrap Estimates</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Method</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Jackknife</td>
<td style="text-align: right;">52.5000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bootstrap</td>
<td style="text-align: right;">19.2889</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Something fishy here?</p>
<p>Clearly something is wrong here, because the bootstrap estimate and the jackknife estimate are far apart. The jackknife fails because the median is <em>not smooth</em>.</p>
</div>
<p>In this case, when the statistic is not smooth, the delete-d jackknife can be applied. If <span class="math inline">\(\sqrt{n}/{d}\to 0\)</span> and <span class="math inline">\(n − d\to\infty\)</span>, then the delete-d jackknife is consistent for the median. The computing time increases because there are a large number of jackknife replicates when <span class="math inline">\(n\)</span> and <span class="math inline">\(d\)</span> are large.</p>
</section>
<section id="other-variations-of-the-jackknife-estimations" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="other-variations-of-the-jackknife-estimations"><span class="header-section-number">6.6.4</span> Other variations of the Jackknife estimations</h3>
<ul>
<li>Jackknife ++</li>
<li>Weighted Jackknife</li>
<li>Block jackknife</li>
</ul>
</section>
</section>
<section id="bootstrap-confidence-interval" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="bootstrap-confidence-interval"><span class="header-section-number">6.7</span> Bootstrap Confidence Interval</h2>
<p>In this section, we introduce a several approaches to obtaining approximate confidence intervals (CIs) for the target parameter in a bootstrap. The methods include</p>
<ol type="1">
<li>standard normal bootstrap CI,</li>
<li>basic bootstrap CI</li>
<li>bootstrap percentile CI</li>
<li>bootstrap t confidence interval</li>
</ol>
<section id="standard-normal-bootstrap-ci" class="level3" data-number="6.7.1">
<h3 data-number="6.7.1" class="anchored" data-anchor-id="standard-normal-bootstrap-ci"><span class="header-section-number">6.7.1</span> Standard Normal Bootstrap CI</h3>
<p>he standard normal bootstrap confidence interval is the simplest approach, but not necessarily the best. Suppose that <span class="math inline">\(\hat \theta\)</span> is an estimator of parameter θ, and assume the standard error of the estimator is <span class="math inline">\(se(\hat \theta)\)</span>. If <span class="math inline">\(\hat \theta\)</span> is a sample mean and the sample size is large, then the CLT implies that <span class="math display">\[
\frac{\hat{\theta}-\mathbb E[\hat \theta]}{s e(\hat{\theta})} \approx N(0,1)=Z.
\]</span> Hence, if <span class="math inline">\(\hat \theta\)</span> is unbiased of <span class="math inline">\(\theta\)</span>, then an approximate <span class="math inline">\(100(1-\alpha)\)</span>% CI for <span class="math inline">\(\theta\)</span> is given by <span class="math display">\[
\hat \theta\pm z_{1-\alpha / 2} s e(\hat \theta),
\]</span> Advantage:</p>
<ul>
<li>easy to compute</li>
</ul>
<p>Disadvantage: requires several assumptions.</p>
<ol type="1">
<li><span class="math inline">\(\hat \theta\sim N\)</span> or <span class="math inline">\(\hat \theta\)</span> is a sample mean and <span class="math inline">\(n\)</span> is large.</li>
<li><span class="math inline">\(\mathbb E[\hat \theta]=\theta\)</span>.</li>
</ol>
<p>Bias can be estimated and used to center the Z statistic, but the estimator is a rv, so the transformed variable is not normal. Here we have treated <span class="math inline">\(se(\hat \theta)\)</span> as a <em>known parameter</em>, but in the bootstrap <span class="math inline">\(se(\hat \theta)\)</span> is estimated (the sample standard deviation of the replicates).</p>
</section>
<section id="basic-bootstrap-ci" class="level3" data-number="6.7.2">
<h3 data-number="6.7.2" class="anchored" data-anchor-id="basic-bootstrap-ci"><span class="header-section-number">6.7.2</span> Basic Bootstrap CI</h3>
<p>The basic bootstrap CI interval transforms the distribution of the replicates by <strong>subtracting the observed statistic</strong>. The quantiles of the transformed sample <span class="math inline">\(\hat \theta^\ast-\hat \theta\)</span> are used to determine the confidence limits.</p>
<p>The <span class="math inline">\(100(1 − \alpha)\)</span>% confidence limits for the basic bootstrap confidence interval are <span class="math display">\[
\boxed{
(2\hat \theta- \hat \theta^
\ast_{1-\alpha/2},\quad 2\hat \theta- \hat \theta^
\ast_{\alpha/2})},
\]</span> whee re <span class="math inline">\(\hat \theta^\ast_q\)</span> is the <span class="math inline">\(q\)</span>th quantile of the bootstrap replicates <span class="math inline">\(\hat \theta^{(1)},\dots ,\hat \theta^{(B)}\)</span>.</p>
<div id="callout-8" class="callout callout-style-default callout-note callout-titled" title="Derivation of the Basic Bootstrap CI">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Derivation of the Basic Bootstrap CI
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let <span class="math inline">\(\mathbf{x}= (x_1,\dots,x_n)\)</span> be the observed sample, and a statistics <span class="math inline">\(\hat \theta= T_n(\mathbf{x})\)</span> be the estimator of the parameter of interest <span class="math inline">\(\theta\)</span> of the sampling distribution. Assume that we have <span class="math inline">\(B\)</span> replicates <span class="math inline">\(\hat \theta^\ast\)</span> from bootstrap.</p>
<p>To obtain a <strong>symmetric</strong> <span class="math inline">\(100(1-\alpha)\)</span>% CI for <span class="math inline">\(\theta\)</span>, say <span class="math inline">\((L,U)\)</span>, we know that we need <span class="math display">\[
P(U \le \theta)= P(\theta \le L)=\alpha/2.
\]</span> Then, we have <span class="math display">\[
\alpha/2 = P(L \ge \theta) = P(L-\hat \theta\ge \theta - \hat \theta) = P(\hat \theta- \theta \le \hat \theta- L).
\]</span></p>
<p>Now, we have to solve it, we need <span class="math inline">\(L-\hat \theta\)</span> be the <span class="math inline">\(1-\alpha/2\)</span>’s quantile of the distribution of <span class="math inline">\(\hat \theta- \theta\)</span>. However, the distribution of <span class="math inline">\(\hat \theta- \theta\)</span> is <em>unknown</em>. In bootstrap, we approximate the distribution of <span class="math inline">\(\hat \theta- \theta\)</span> by the distribution of <span class="math inline">\(\hat \theta^\ast - \hat \theta\)</span>. Thus, we set <span class="math inline">\(\hat \theta- L\)</span> to be the <span class="math inline">\(1-\alpha/2\)</span>’s quantile of the distribution of <span class="math inline">\(\hat \theta^\ast - \hat \theta\)</span>, denoted as <span class="math inline">\(\hat \theta^\ast_{1-\alpha/2}\)</span>, that is, <span class="math inline">\(\hat \theta^\ast_{1-\alpha/2}-\hat \theta\)</span>. Then, we set <span class="math inline">\(\hat \theta-L\)</span> to be <span class="math inline">\(\hat \theta^\ast_{1-\alpha/2}-\hat \theta\)</span>.</p>
<p>Similarly, for the upper limit <span class="math inline">\(U\)</span>, we have <span class="math display">\[
\alpha/2 = P(\theta \ge U) = P(\theta - \hat \theta\ge U - \hat \theta) = P(\hat \theta- \theta \le \hat \theta- U),
\]</span> which leads to <span class="math inline">\(\hat \theta-U = \hat \theta_{\alpha/2}^\ast - \hat \theta\)</span>. We *move <span class="math inline">\(\hat \theta\)</span> to other side for both <span class="math inline">\(L\)</span> and <span class="math inline">\(U\)</span>. As a result, we obtain <span class="math display">\[
(L,~U) = (2\hat \theta- \hat \theta^\ast_{1-\alpha/2},~2\hat \theta- \hat \theta^\ast_{\alpha/2}),
\]</span> which is the result of a basic bootstrap CI we state previously.</p>
</div>
</div>
</section>
<section id="bootstrap-percentile-ci" class="level3" data-number="6.7.3">
<h3 data-number="6.7.3" class="anchored" data-anchor-id="bootstrap-percentile-ci"><span class="header-section-number">6.7.3</span> Bootstrap Percentile CI</h3>
<p>This method use directly from the empirical distribution.</p>
<p>A bootstrap percentile interval uses the empirical distribution of the bootstrap replicates as the reference distribution. The quantiles of the empirical distribution are estimators of the quantiles of the sampling distribution of <span class="math inline">\(\hat \theta\)</span>, so that these (random) quantiles may match the true distribution better when the distribution of <span class="math inline">\(\hat \theta\)</span> is <strong>not normal</strong>. Suppose that <span class="math inline">\(\{\hat \theta^{(b)}\}_{b=1}^B\)</span> are the bootstrap replicates of the statistic <span class="math inline">\(\hat \theta\)</span>. From the ecdf of the replicates, compute the <span class="math inline">\(\alpha/2\)</span> quantile <span class="math inline">\(\hat \theta_{\alpha/2}\)</span>, and the <span class="math inline">\(1 − \alpha/2\)</span> quantile <span class="math inline">\(\hat \theta_{1-\alpha/2}\)</span>.</p>
<p>Researchers showed that this method some theoretical advantages over the standard normal interval and somewhat better coverage performance in practice.</p>
<div id="callout-9" class="callout callout-style-default callout-note callout-titled" title="R command">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>R command
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>boot::boot.ci(.)</code> computes 5 types of bootstrap CI:</p>
<ol type="1">
<li>basic</li>
<li>normal</li>
<li>percentile</li>
<li>studentized</li>
<li>BCa (bias-corrected and accelerated), which is an improved percentile intervals that aim to have better theoretical properties and better performance in practice.</li>
</ol>
</div>
</div>
<div class="callout-example" title="Bootstrap CIs on the patch ratio statistics">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">8670</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(patch, <span class="at">package =</span> <span class="st">"bootstrap"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># function to compute the statistic</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>theta.boot <span class="ot">&lt;-</span> <span class="cf">function</span>(dat, ind) {</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> dat[ind, <span class="dv">1</span>]</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> dat[ind, <span class="dv">2</span>]</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(y) <span class="sc">/</span> <span class="fu">mean</span>(z)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> patch<span class="sc">$</span>y</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> patch<span class="sc">$</span>z</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(y, z)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>boot.obj <span class="ot">&lt;-</span> <span class="fu">boot</span>(dat, <span class="at">statistic =</span> theta.boot, <span class="at">R =</span> <span class="dv">2000</span>)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(boot.obj)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = dat, statistic = theta.boot, R = 2000)


Bootstrap Statistics :
      original     bias    std. error
t1* -0.0713061 0.01265825   0.1047968</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">boot.ci</span>(boot.obj,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"basic"</span>, <span class="st">"norm"</span>, <span class="st">"perc"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 2000 bootstrap replicates

CALL : 
boot.ci(boot.out = boot.obj, type = c("basic", "norm", "perc"))

Intervals : 
Level      Normal              Basic              Percentile     
95%   (-0.2894,  0.1214 )   (-0.3422,  0.0839 )   (-0.2265,  0.1995 )  
Calculations and Intervals on Original Scale</code></pre>
</div>
</div>
<p>Recall that the old and new patches are bioequivalent if |θ| ≤ 0.20. Hence, the interval estimates do not support bioequivalence of the old and new patches. Next we compute the bootstrap confidence intervals according to their defini- tions. Compare the following results with the boot.ci output.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># normal</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>CI_normal <span class="ot">&lt;-</span> boot.obj<span class="sc">$</span>t0 <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>)) <span class="sc">*</span> <span class="fu">sd</span>(boot.obj<span class="sc">$</span>t)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># basic</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>CI_basic <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> boot.obj<span class="sc">$</span>t0 <span class="sc">-</span> <span class="fu">quantile</span>(boot.obj<span class="sc">$</span>t, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>, alpha<span class="sc">/</span><span class="dv">2</span>), <span class="at">type =</span> <span class="dv">1</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co"># percentile</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>CI_percentile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(boot.obj<span class="sc">$</span>t, <span class="at">probs =</span> <span class="fu">c</span>(alpha<span class="sc">/</span><span class="dv">2</span>, <span class="dv">1</span> <span class="sc">-</span> alpha<span class="sc">/</span><span class="dv">2</span>), <span class="at">type =</span> <span class="dv">6</span>)</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co"># combine into data frame</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>CI_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">Method =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Basic"</span>, <span class="st">"Percentile"</span>),</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">Lower =</span> <span class="fu">c</span>(CI_normal[<span class="dv">1</span>], CI_basic[<span class="dv">1</span>], CI_percentile[<span class="dv">1</span>]),</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">Upper =</span> <span class="fu">c</span>(CI_normal[<span class="dv">2</span>], CI_basic[<span class="dv">2</span>], CI_percentile[<span class="dv">2</span>])</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="co"># display as kable</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(CI_table, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">caption =</span> <span class="st">"Bootstrap Confidence Intervals"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Bootstrap Confidence Intervals</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Lower</th>
<th style="text-align: right;">Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Normal</td>
<td style="text-align: right;">-0.2713</td>
<td style="text-align: right;">0.1287</td>
</tr>
<tr class="even">
<td style="text-align: left;">97.5%</td>
<td style="text-align: left;">Basic</td>
<td style="text-align: right;">-0.3077</td>
<td style="text-align: right;">0.0876</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2.5%</td>
<td style="text-align: left;">Percentile</td>
<td style="text-align: right;">-0.2302</td>
<td style="text-align: right;">0.1674</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="callout-10" class="callout callout-style-default callout-note callout-titled" title="Remark">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Remark
</div>
</div>
<div class="callout-body-container callout-body">
<p>The normal interval computed by boot.ci corrects for bias. Notice that the boot.ci normal interval differs from our result by the bias estimate shown in the output from boot. This is confirmed by read- ing the source code for the function. To view the source code for this calculation, when the boot package is loaded, enter the command getAnywhere(norm.ci) at the console. Also see norm.inter and [68] for details of calculations of quantiles.</p>
</div>
</div>
<div class="callout-example" title="Bootstrap CIs for correlation coefficients">
<p>Example 8.10 (Bootstrap confidence intervals for the correlation statis- tic). Compute 95% bootstrap confidence interval estimates for the correlation statistic in the law data of Example 8.2.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(law, <span class="at">package =</span> <span class="st">"bootstrap"</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>boot.obj <span class="ot">&lt;-</span> <span class="fu">boot</span>(law,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">R =</span> <span class="dv">2000</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">statistic =</span> <span class="cf">function</span>(x, i) {</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cor</span>(x[i, <span class="dv">1</span>], x[i, <span class="dv">2</span>])</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">boot.ci</span>(boot.obj, </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">type =</span> <span class="fu">c</span>(<span class="st">"basic"</span>, <span class="st">"norm"</span>, <span class="st">"perc"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 2000 bootstrap replicates

CALL : 
boot.ci(boot.out = boot.obj, type = c("basic", "norm", "perc"))

Intervals : 
Level      Normal              Basic              Percentile     
95%   ( 0.5151,  1.0364 )   ( 0.5901,  1.0946 )   ( 0.4582,  0.9627 )  
Calculations and Intervals on Original Scale</code></pre>
</div>
</div>
<p>All three intervals cover the correlation <span class="math inline">\(\rho=0.76\)</span> of the universe of all law schools in law82. One reason for the difference in the percentile and normal confidence intervals could be that the sampling distribution of correlation statistic is not close to normal (see the histogram in Figure 8.1). When the sampling distribution of the statistic is approximately normal, the percentile interval will agree with the normal interval.</p>
</div>
</section>
<section id="bootstrap-t-ci" class="level3" data-number="6.7.4">
<h3 data-number="6.7.4" class="anchored" data-anchor-id="bootstrap-t-ci"><span class="header-section-number">6.7.4</span> Bootstrap t CI</h3>
<p>Even if the distribution of <span class="math inline">\(\hat \theta\)</span> is normal and <span class="math inline">\(\mathbb E[\hat \theta]=\theta\)</span>, the normal distribution is not exactly correct for the Z statistic, because we estimate <span class="math inline">\(se(\hat \theta)\)</span>. Nor can we claim that it is a Student t statistic, because the distribution of the bootstrap estimator <span class="math inline">\(se(\hat \theta)\)</span> is unknown. <strong>The bootstrap t interval does not use a Student t distribution as the reference distribution</strong>. Instead, the sampling distribution of a <em>t type</em> statistic (a studentized statistic) is generated by resampling. Let <span class="math inline">\(\mathbf{x}= (x_1, \dots, x_n)\)</span> be an observed sample. The <span class="math inline">\(100(1 − \alpha)\)</span>% bootstrap t confidence interval is <span class="math display">\[
\boxed{
\left(\hat{\theta}-t_{1-\alpha / 2}^* \widehat{s e}(\hat{\theta}), \quad \hat{\theta}-t_{\alpha / 2}^* \widehat{s e}(\hat{\theta})\right)},
\]</span></p>
<p>where <span class="math inline">\(se(\hat \theta),~ t^\ast_{\alpha/2}\)</span> and <span class="math inline">\(t^\ast_{1-\alpha/2}\)</span> are computed as outlined below.</p>
<div class="callout-algorithm" title="Algorithm of Bootstrap t CI">
<ol type="1">
<li>Compute the observed statistic <span class="math inline">\(\hat \theta\)</span>.</li>
<li>For each replicate, indexed <span class="math inline">\(b = 1, \dots,B\)</span>:</li>
</ol>
<ol type="a">
<li>Sample with replacement from x to get the bth sample <span class="math inline">\(\mathbf{x}^{(b)} = (x_1^{(b)}, \dots , x_n^{(b)})\)</span></li>
<li>Compute <span class="math inline">\(\hat \theta^{(b)}\)</span> from the <span class="math inline">\(b\)</span>th sample <span class="math inline">\(x^{(b)}\)</span>.</li>
<li>Compute or estimate the standard error <span class="math inline">\(\widehat{se}(\hat \theta^{(b)})\)</span> (a separate estimate for each bootstrap sample; a bootstrap estimate will resample from the current bootstrap sample <span class="math inline">\(\mathbf{x}^{(b)}\)</span>, not <span class="math inline">\(\mathbf{x}\)</span>).</li>
<li>Compute the <span class="math inline">\(b\)</span>th replicate of the <em>t</em> statistic, <span class="math display">\[t(b) = \frac{\hat \theta^{(b)}−\hat \theta}{\widehat{se}(\hat \theta^{(b)})}.\]</span></li>
</ol>
<ol start="3" type="1">
<li>The sample of replicates <span class="math inline">\(t^{(1)},\dots t^{(B)}\)</span> is the reference distribution for bootstrap <span class="math inline">\(t\)</span>. Find the sample quantiles <span class="math inline">\(t^\ast_{\alpha/2}\)</span> and <span class="math inline">\(t^\ast_{1-\alpha/2}\)</span> from the ordered sample of replicates <span class="math inline">\(t^{(b)}\)</span>.</li>
<li>Compute <span class="math inline">\(\widehat{\hat \theta}\)</span>, the sample standard deviation of the replicates <span class="math inline">\(\hat \theta^{(b)}\)</span>.</li>
<li>Compute confidence limits <span class="math display">\[
\left(\hat{\theta}-t_{1-\alpha / 2}^* \widehat{\operatorname{se }}(\hat{\theta}), \quad \hat{\theta}-t_{\alpha / 2}^* \widehat{\operatorname{se}}(\hat{\theta})\right) .
\]</span></li>
</ol>
</div>
<p>One disadvantage is the <em>computational time</em>!</p>
<p>To the bootstrap <span class="math inline">\(t\)</span> interval, typically <span class="math inline">\(\widehat{se}(\hat \theta^{(b)})\)</span> must be obtained by bootstrap. This is <em>a bootstrap nested inside a bootstrap</em>. If <span class="math inline">\(B = 1000\)</span>, for example, the bootstrap t confidence interval method takes approximately <span class="math inline">\(1000\)</span> times longer than any of the other methods.</p>
<hr>
<p>Here, we see how to compute the bootstrap <span class="math inline">\(t\)</span> confidence interval for a univariate or a multivariate sample <span class="math inline">\(\mathbf{x}\)</span>. The required arguments to the function are</p>
<ul>
<li>the sample data <span class="math inline">\(\mathbf{x}\)</span>, and</li>
<li>the function statistic that computes the statistic <span class="math inline">\(T_n(\mathbf{x})\)</span>.</li>
</ul>
<p>The default values are:</p>
<ul>
<li>significance level is <span class="math inline">\(\alpha=0.05\)</span></li>
<li>number of bootstrap replicates <span class="math inline">\(B=500\)</span>,</li>
<li>number of replicates for estimating standard error is <span class="math inline">\(100\)</span>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>boot.t.ci <span class="ot">&lt;-</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(x, <span class="at">B =</span> <span class="dv">500</span>, <span class="at">R =</span> <span class="dv">100</span>, <span class="at">level =</span> .<span class="dv">95</span>, statistic) {</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># compute the bootstrap t CI</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(x)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(x)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    stat <span class="ot">&lt;-</span> <span class="fu">numeric</span>(B)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    se <span class="ot">&lt;-</span> <span class="fu">numeric</span>(B)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    boot.se <span class="ot">&lt;-</span> <span class="cf">function</span>(x, R, f) {</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>      <span class="co"># local function to compute the bootstrap</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>      <span class="co"># estimate of standard error for statistic f(x)</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>      x <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(x)</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>      m <span class="ot">&lt;-</span> <span class="fu">nrow</span>(x)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>      th <span class="ot">&lt;-</span> <span class="fu">replicate</span>(R, <span class="at">expr =</span> {</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>        i <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>m, <span class="at">size =</span> m, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>        <span class="fu">f</span>(x[i, ])</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>      })</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>      <span class="fu">return</span>(<span class="fu">sd</span>(th))</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (b <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>      j <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>      y <span class="ot">&lt;-</span> x[j, ]</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>      stat[b] <span class="ot">&lt;-</span> <span class="fu">statistic</span>(y)</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>      se[b] <span class="ot">&lt;-</span> <span class="fu">boot.se</span>(y, <span class="at">R =</span> R, <span class="at">f =</span> statistic)</span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>    stat0 <span class="ot">&lt;-</span> <span class="fu">statistic</span>(x)</span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>    t.stats <span class="ot">&lt;-</span> (stat <span class="sc">-</span> stat0) <span class="sc">/</span> se</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>    se0 <span class="ot">&lt;-</span> <span class="fu">sd</span>(stat)</span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>    alpha <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> level</span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>    Qt <span class="ot">&lt;-</span> <span class="fu">quantile</span>(t.stats, <span class="fu">c</span>(alpha <span class="sc">/</span> <span class="dv">2</span>, <span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>), <span class="at">type =</span> <span class="dv">1</span>)</span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">names</span>(Qt) <span class="ot">&lt;-</span> <span class="fu">rev</span>(<span class="fu">names</span>(Qt))</span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a>    CI <span class="ot">&lt;-</span> <span class="fu">rev</span>(stat0 <span class="sc">-</span> Qt <span class="sc">*</span> se0)</span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>  }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We then aim to apply this function to our problem in hand.</p>
<div class="callout-example" title="Bootstrap t CI for patch ratio statistics">
<p>Now, we want to compute a 95% bootstrap <span class="math inline">\(t\)</span> confidence interval for the ratio statistic we discussed previously.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(patch<span class="sc">$</span>y, patch<span class="sc">$</span>z)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>stat <span class="ot">&lt;-</span> <span class="cf">function</span>(dat) {</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(dat[, <span class="dv">1</span>]) <span class="sc">/</span> <span class="fu">mean</span>(dat[, <span class="dv">2</span>])</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">boot.t.ci</span>(dat, <span class="at">statistic =</span> stat, <span class="at">B =</span> <span class="dv">2000</span>, </span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">R =</span> <span class="dv">200</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ci)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2.5%      97.5% 
-0.2733909  0.4381807 </code></pre>
</div>
</div>
<p>The upper confidence limit of the bootstrap <span class="math inline">\(t\)</span> confidence interval is much larger than the three intervals in Example 9 and the bootstrap <span class="math inline">\(t\)</span> is the widest interval here.</p>
</div>
</section>
</section>
<section id="others" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="others"><span class="header-section-number">6.8</span> Others</h2>
<p>There are other method to construct bootstrap CIs. Interested reader should read the reference book, Davison &amp; Hinkley (1997).</p>
<!-- ---  -->
<!-- The distribution of $X^\ast$ is the empirical distribution $F_n$ of the sample $x$. The empirical distribution places mass $1/n$ at each observed data point. The bootstrap uses the empirical distribution as an estimate of the true but unknown distribution $F$. -->
<!-- The bootstrap is a resampling method that allows estimation of the *sampling distribution* of almost any statistic using random sampling methods. -->
<!-- -   Parametric bootstrap -->
<!-- -   Nonparametric bootstrap: In nonparametric bootstrap, the distribution is not specified. -->
<!-- ::: {.callout-example title="Simple example of Bootstrap"} -->
<!-- ```{r bootstrap-simple-example} -->
<!-- set.seed(333) -->
<!-- n <- 1E4 -->
<!-- B <- 1E4 -->
<!-- x <- rnorm(n, mean = 5, sd = 2) #original sample -->
<!-- boot_means <- pbapply::pbsapply(1:B, function(i){ -->
<!--   indices <- sample(1:n, size = n, replace = TRUE) #resample -->
<!--   boot.sample <- x[indices] -->
<!--   mean(boot.sample) -->
<!-- }) -->
<!-- mean(boot_means) -->
<!-- hist(boot_means, breaks = 50, main = "Bootstrap distribution of the mean", xlab = "Mean") -->
<!-- # Compute statistics -->
<!-- true_mean <- 5 -->
<!-- boot_mean <- mean(boot_means) -->
<!-- df <- tibble(x = boot_means) -->
<!-- # Plot -->
<!-- ggplot(df, aes(x = x)) + -->
<!--   geom_histogram(aes(y = ..density..), bins = 50, -->
<!--                  fill = "lightgreen", color = "black", alpha = 0.7) + -->
<!--   geom_density(color = "darkgreen", size = 1) + -->
<!--   geom_vline(xintercept = true_mean, color = "red", linetype = "dashed", size = 1.1) + -->
<!--   geom_vline(xintercept = boot_mean, color = "blue", linetype = "solid", size = 1.1) + -->
<!--   labs( -->
<!--     title = "Bootstrap Distribution of the Sample Mean", -->
<!--     x = "Bootstrap Mean", -->
<!--     y = "Density" -->
<!--   ) + -->
<!--   annotate("text", x = true_mean, y = 0.3, label = "True mean = 5", color = "red", hjust = -0.1) + -->
<!--   annotate("text", x = boot_mean, y = 0.25, label = sprintf("Bootstrap mean = %.2f", boot_mean), -->
<!--            color = "blue", hjust = -0.1) + -->
<!--   theme_minimal(base_size = 14) -->
<!-- ``` -->
<!-- ::: -->
<!-- The bootstrap is a general tool for assessing statistical accuracy. First we describe the bootstrap in general, and then show how it can be used to estimate extra-sample prediction error. As with cross-validation, the boot- strap seeks to estimate the conditional error ErrT , but typically estimates well only the expected prediction error Err. -->
<!-- The distribution of the finite population represented by the sample can be regarded as a pseudo-population with similar characteristics as the true population. By repeatedly generating random samples from this pseudo-population (resampling), the sampling distribution of a statistic can be estimated. Properties of an estimator such as *bias* or *standard error* can be estimated by resampling. -->
<!-- Bootstrap estimates of a sampling distribution are analogous to the idea of density estimation. We construct a histogram of a sample to obtain an estimate of the shape of the density function. The histogram is not the density, but in a nonparametric problem, can be viewed as a reasonable estimate of the density. We have methods to generate random samples from completely specified densities; bootstrap generates random samples from the empirical distribution of the sample. -->
<!-- The term *bootstrap* can refer to nonparametric bootstrap or parametric bootstrap. Monte Carlo methods that involve sampling from a fully specified probability distribution, such as methods of Chapter 7 are sometimes called parametric bootstrap. Nonparametric bootstrap is the subject of this chapter. In nonparametric bootstrap, the distribution is not specified. -->
<!-- To generate a bootstrap random sample by resampling $x$, generate n random integers $\{i_1,\dots, i_n\}$ uniformly distributed on $\{1,\dots , n\}$ and select the bootstrap sample $x^∗ = (x_{i_1} ,\dots, x_{i_n} )$. Suppose $\theta$ is the parameter of interest ($\theta$ could be a vector), and $\hat \theta$ is an estimator of $\theta$. Then the bootstrap estimate of the distribution of $\hat \theta$ is obtained as follows. -->
<!-- ## Applications -->
<!-- These methods are widely used in statistical inference and have applications in various fields. -->
</section>
<section id="side-reading-wont-be-on-the-exam" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="side-reading-wont-be-on-the-exam"><span class="header-section-number">6.9</span> Side reading (Won’t be on the exam)</h2>
<div id="callout-11" class="callout callout-style-default callout-note callout-titled" title="Normal theory for SE (will not be on exam)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Normal theory for SE (will not be on exam)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Normal Approximation for Correlation SE</p>
<p>For a bivariate normal population, the sampling distribution of the sample correlation <span class="math inline">\(r\)</span> is approximately normal with variance</p>
<p><span class="math display">\[
\operatorname{Var}(r) \approx \frac{(1 - \rho^2)^2}{n - 1}.
\]</span></p>
<p>Thus, the <strong>standard error (SE)</strong> under the normal approximation is</p>
<p><span class="math display">\[
\operatorname{se}_{\text{normal}}(r) = \sqrt{\frac{(1 - r^2)^2}{n - 1}}.
\]</span></p>
<p>In the Law school example</p>
<p>Given: - <span class="math inline">\(r = 0.7763745\)</span> - <span class="math inline">\(n = 15\)</span></p>
<p>We can compute:</p>
<p><span class="math display">\[
1 - r^2 = 1 - (0.776)^2 = 1 - 0.602 = 0.398,
\]</span> <span class="math display">\[
\operatorname{Var}(r) \approx \frac{(0.398)^2}{14} = \frac{0.158}{14} = 0.0113,
\]</span> <span class="math display">\[
\operatorname{se}(r) = \sqrt{0.0113} = 0.106.
\]</span></p>
<p>This gives a rough normal-theory estimate of <strong>0.106</strong>.</p>
<ul>
<li>For Fisher z-Transformation Approximation</li>
</ul>
<p>A more accurate approximation uses the <strong>Fisher z-transform</strong>:</p>
<p><span class="math display">\[
z = \frac{1}{2}\log\!\left(\frac{1 + r}{1 - r}\right),
\]</span></p>
<p>which is approximately normal with</p>
<p><span class="math display">\[
\operatorname{Var}(z) = \frac{1}{n - 3}.
\]</span></p>
<p>Applying the delta method:</p>
<p><span class="math display">\[
\operatorname{se}(r) \approx (1 - r^2)\sqrt{\frac{1}{n - 3}}.
\]</span></p>
<p>Plug in the values:</p>
<p><span class="math display">\[
\operatorname{se}(r) = (1 - 0.776^2)\sqrt{\frac{1}{12}} = 0.398 \times 0.289 = 0.115.
\]</span></p>
<p>✅ <strong>Normal approximation (Fisher z) SE = 0.115</strong></p>
<p>Alternatively, we may use the <strong>Bootstrap Estimate</strong> to compare with:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(bootstrap) <span class="co"># for the law data</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample data</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>law <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">LSAT =</span> <span class="fu">c</span>(<span class="dv">576</span>, <span class="dv">635</span>, <span class="dv">558</span>, <span class="dv">578</span>, <span class="dv">666</span>, <span class="dv">580</span>, <span class="dv">555</span>, <span class="dv">661</span>, <span class="dv">651</span>, <span class="dv">605</span>, <span class="dv">653</span>, <span class="dv">575</span>, <span class="dv">545</span>, <span class="dv">572</span>, <span class="dv">594</span>),</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">GPA  =</span> <span class="fu">c</span>(<span class="dv">339</span>, <span class="dv">330</span>, <span class="dv">281</span>, <span class="dv">303</span>, <span class="dv">344</span>, <span class="dv">307</span>, <span class="dv">300</span>, <span class="dv">343</span>, <span class="dv">336</span>, <span class="dv">313</span>, <span class="dv">312</span>, <span class="dv">274</span>, <span class="dv">276</span>, <span class="dv">288</span>, <span class="dv">296</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample correlation</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>(law<span class="sc">$</span>LSAT, law<span class="sc">$</span>GPA)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(law)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap estimate of SE</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="fu">replicate</span>(B, {</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(law<span class="sc">$</span>LSAT[i], law<span class="sc">$</span>GPA[i])</span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>se_boot <span class="ot">&lt;-</span> <span class="fu">sd</span>(R)</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Normal approximation</span></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>se_normal <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((<span class="dv">1</span> <span class="sc">-</span> r<span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (n <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Fisher z-approximation</span></span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a>se_fisher <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> r<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(n <span class="sc">-</span> <span class="dv">3</span>)</span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb38-30"><a href="#cb38-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">Method =</span> <span class="fu">c</span>(<span class="st">"Bootstrap"</span>, <span class="st">"Normal theory"</span>, <span class="st">"Fisher z-approximation"</span>),</span>
<span id="cb38-31"><a href="#cb38-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">SE =</span> <span class="fu">c</span>(se_boot, se_normal, se_fisher)</span>
<span id="cb38-32"><a href="#cb38-32" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Method        SE
1              Bootstrap 0.1200175
2          Normal theory 0.1061676
3 Fisher z-approximation 0.1146741</code></pre>
</div>
</div>
<hr>
<section id="reference" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="reference"><span class="header-section-number">6.10</span> Reference:</h2>
<ul>
<li><p>Davison, A.C. and Hinkley, D.V. (1997). <a href="https://www.cambridge.org/core/books/bootstrap-methods-and-their-application/ED2FD043579F27952363566DC09CBD6A">Bootstrap Methods and their Application</a>. Cambridge University Press.</p></li>
<li><p>Section 7.11 in Hastie, T., Tibshirani R. and Friedman, J. (2008). <a href="https://www.sas.upenn.edu/~fdiebold/NoHesitations/BookAdvanced.pdf">The Elements of Statistical Learning</a>. Springer, 2nd edition.</p></li>
<li><p>Chapter 8 of Rizzo, M.L. (2007). <em>Statistical Computing with R</em>. CRC Press, Roca Baton.</p></li>
<li><p>Wu, C.F.J. (1986).<a href="https://projecteuclid.org/journals/annals-of-statistics/volume-14/issue-4/Jackknife-Bootstrap-and-Other-Resampling-Methods-in-Regression-Analysis/10.1214/aos/1176350142.full">Bootstrap and Other Resampling Methods in Regression Analysis</a>. <em>The Annals of Statistics</em>.</p></li>
</ul>
<hr>
</section>
<section id="r-functions" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="r-functions"><span class="header-section-number">6.11</span> R Functions</h2>
<p>Some useful R functions for resampling methods:</p>
<ul>
<li><p><code>sample()</code>: Generate random samples from a specified set of data points.</p></li>
<li><p><code>boot::boot()</code>: Perform bootstrap resampling and compute statistics.</p></li>
<li><p><code>bootstrap</code>: A package that is associated with the book by Efron and Tibshirani (1993). It contains variety of the functions for bootstrap and jackknife, and the dataset used in the book.</p></li>
</ul>
</section>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-cv.html" class="pagination-link" aria-label="Cross Validation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Cross Validation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-smoothing.html" class="pagination-link" aria-label="Smoothing Techniques in Statistics">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Smoothing Techniques in Statistics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>